### ISSUE TITLE
bug(sdk) References to custom task outputs are lowercased

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#1007]
/kind bug

**What steps did you take and what happened:**
Create a custom task with uppercase inputs and outputs. Pass that output to some task.
```python
import itertools

from kfp import dsl, components
from kfp_tekton.tekton import TEKTON_CUSTOM_TASK_IMAGES
from kfp_tekton.compiler import TektonCompiler
import yaml


ARTIFACT_FETCHER_IMAGE_NAME = "fetcher/image:latest"
TEKTON_CUSTOM_TASK_IMAGES = TEKTON_CUSTOM_TASK_IMAGES.append(ARTIFACT_FETCHER_IMAGE_NAME)

_artifact_fetcher_no = 0

def artifact_fetcher(**artifact_paths: str):
  '''A containerOp template resolving some artifacts, given their paths.'''
  global _artifact_fetcher_no
  template_yaml = {
    'name': f'artifact-fetcher-{_artifact_fetcher_no}',
    'description': 'Artifact Fetch',
    'inputs': [
      {'name': name, 'type': 'String'}
      for name in artifact_paths.keys()
    ],
    'outputs': [
      {'name': name, 'type': 'Artifact'}
      for name in artifact_paths.keys()
    ],
    'implementation': {
      'container': {
        'image': ARTIFACT_FETCHER_IMAGE_NAME,
        'command': ['sh', '-c'], # irrelevant
        'args': [
          '--apiVersion', 'fetcher.tekton.dev/v1alpha1',
          '--kind', 'FETCHER',
          '--name', 'artifact_fetcher',
          *itertools.chain(*[
            (f'--{name}', {'inputValue': name})
            for name in artifact_paths.keys()
          ])
        ]
      }
    }
  }
  _artifact_fetcher_no += 1
  template_str = yaml.dump(template_yaml, Dumper=yaml.SafeDumper)
  template = components.load_component_from_text(template_str)
  op = template(**{
    k.lower(): v for k,v in artifact_paths.items()
  })
  op.add_pod_annotation("valid_container", "false")
  return op

_artifact_printer_no = 0

def artifact_printer(artifact):
  global _artifact_printer_no
  template_yaml = {
    'name': f'artifact-printer-{_artifact_printer_no}',
    'description': 'Artifact Fetch',
    'inputs': [
      {'name': 'artifact', 'type': 'Artifact'}
    ],
    'outputs': [
      {'name': 'stdout', 'type': 'String'}
    ],
    'implementation': {
      'container': {
        'image': 'alpine:3.6',
        'command': [
          'echo',
          {'inputValue': 'artifact'},
          '>',
          {'outputPath': 'stdout'}
        ]
      }
    }
  }
  _artifact_printer_no += 1
  template_str = yaml.dump(template_yaml, Dumper=yaml.SafeDumper)
  template = components.load_component_from_text(template_str)
  op = template(artifact)
  return op


@dsl.pipeline("uppercase vs lowercase")
def uppercase_vs_lowercase():
  fetch_upper = artifact_fetcher(FOO='FOO')
  fetch_lower = artifact_fetcher(foo='foo')
  print_upper = artifact_printer(fetch_upper.output)
  print_lower = artifact_printer(fetch_lower.output)


if __name__ == '__main__':
  TektonCompiler().compile(uppercase_vs_lowercase, __file__.replace('.py', '.yaml'))
```

This produces the following yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: uppercase-vs-lowercase
  annotations:
    tekton.dev/output_artifacts: '{"artifact-printer-0": [{"key": "artifacts/$PIPELINERUN/artifact-printer-0/stdout.tgz",
      "name": "artifact-printer-0-stdout", "path": "/tmp/outputs/stdout/data"}], "artifact-printer-1":
      [{"key": "artifacts/$PIPELINERUN/artifact-printer-1/stdout.tgz", "name": "artifact-printer-1-stdout",
      "path": "/tmp/outputs/stdout/data"}]}'
    tekton.dev/input_artifacts: '{"artifact-printer-0": [{"name": "artifact-fetcher-0-FOO",
      "parent_task": "artifact-fetcher-0"}], "artifact-printer-1": [{"name": "artifact-fetcher-1-foo",
      "parent_task": "artifact-fetcher-1"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"artifact-printer-0": [["stdout", "$(results.stdout.path)"]],
      "artifact-printer-1": [["stdout", "$(results.stdout.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"name": "uppercase vs lowercase"}'
spec:
  pipelineSpec:
    tasks:
    - name: artifact-fetcher-0
      params:
      - name: FOO
        value: FOO
      taskRef:
        name: artifact_fetcher
        apiVersion: fetcher.tekton.dev/v1alpha1
        kind: FETCHER
      timeout: 525600m
    - name: artifact-fetcher-1
      params:
      - name: foo
        value: foo
      taskRef:
        name: artifact_fetcher
        apiVersion: fetcher.tekton.dev/v1alpha1
        kind: FETCHER
      timeout: 525600m
    - name: artifact-printer-0
      params:
      - name: artifact-fetcher-0-FOO
        value: $(tasks.artifact-fetcher-0.results.foo)
      taskSpec:
        steps:
        - name: main
          command:
          - echo
          - $(inputs.params.artifact-fetcher-0-FOO)
          - '>'
          - $(results.stdout.path)
          image: alpine:3.6
        params:
        - name: artifact-fetcher-0-FOO
        results:
        - name: stdout
          type: string
          description: /tmp/outputs/stdout/data
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "artifact-printer-0",
              "outputs": [{"name": "stdout", "type": "String"}], "version": "artifact-printer-0@sha256=87fc76c64fcc79f4f4b95ee3428ade79e2a4bcdcbc03b4b9b17cef8db6c86dff"}'
            tekton.dev/template: ''
      timeout: 525600m
    - name: artifact-printer-1
      params:
      - name: artifact-fetcher-1-foo
        value: $(tasks.artifact-fetcher-1.results.foo)
      taskSpec:
        steps:
        - name: main
          command:
          - echo
          - $(inputs.params.artifact-fetcher-1-foo)
          - '>'
          - $(results.stdout.path)
          image: alpine:3.6
        params:
        - name: artifact-fetcher-1-foo
        results:
        - name: stdout
          type: string
          description: /tmp/outputs/stdout/data
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "artifact-printer-1",
              "outputs": [{"name": "stdout", "type": "String"}], "version": "artifact-printer-1@sha256=37dc967f8576ece2bc91e571dbaccd7f77043711a66b411d02aa952bd47191bf"}'
            tekton.dev/template: ''
      timeout: 525600m
  timeout: 525600m
```

Note: input/parameter has uppercase name: `FOO`, but the output is referenced to as `$(tasks.artifact-fetcher-0.results.foo)` --- even despite the fact that its consumer named its own input/parameter using uppercase, `artifact-fetcher-0-FOO`.

**What did you expect to happen:**
The output being referred to correctly, using uppercase: `$(tasks.artifact-fetcher-0.results.FOO)`.

**Additional information:**
Looks like an over-eager "sanitization" to me.

**Environment:**

* Python Version (use `python --version`): 3.9.0
* SDK Version: 7d9f8c9a30e84f1bbaa6bfc09e0671c5939b79b0
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
