### ISSUE TITLE
bug(sdk) Any-sequencer in "finally" generates failing yaml

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#1034]
/kind bug

**What steps did you take and what happened:**
Create any number of tasks and plug them into an any-sequencer. Then create an `is_finally=True` `AddOnGroup` and inside of it, recreate the same scenario.

```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.compiler import TektonCompiler
from kfp_tekton.tekton import AddOnGroup, AnySequencer


class ExitHandler(AddOnGroup):
    """A custom OpsGroup which maps to a custom task"""
    def __init__(self):
        labels = {
            'pipelines.kubeflow.org/cache_enabled': 'false',
        }

        super().__init__(
            kind='Exception',
            api_version='custom.tekton.dev/v1alpha1',
            params={},
            is_finally=True,
            labels=labels,
            annotations={},
        )

    def __enter__(self):
        return super().__enter__()

def PrintOp(name: str, msg: str = None):
  if msg is None:
    msg = name
  print_op = load_component_from_text(
  """
  name: %s
  inputs:
  - {name: input_text, type: String, description: 'Represents an input parameter.'}
  outputs:
  - {name: output_value, type: String, description: 'Represents an output paramter.'}
  implementation:
    container:
      image: alpine:3.6
      command:
      - sh
      - -c
      - |
        set -e
        echo $0 > $1
      - {inputValue: input_text}
      - {outputPath: output_value}
  """ % name
  )
  return print_op(msg)

@dsl.pipeline("any-sequencer in finally")
def any_sequencer_in_finally():
  print00 = PrintOp("print-00")
  print01 = PrintOp("print-01")
  AnySequencer([print00, print01])

  with ExitHandler():
      print10 = PrintOp("print-10")
      print11 = PrintOp("print-11")
      AnySequencer([print10, print11])

if __name__ == '__main__':
  TektonCompiler().compile(any_sequencer_in_finally, __file__.replace('.py', '.yaml'))
```

Here is the yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: any-sequencer-in-finally
  annotations:
    tekton.dev/output_artifacts: '{"none": [{"key": "artifacts/$PIPELINERUN/none/None.tgz",
      "name": "none-None", "path": "/tmp/outputs/None/data"}], "none-2": [{"key":
      "artifacts/$PIPELINERUN/none-2/None.tgz", "name": "none-2-None", "path": "/tmp/outputs/None/data"}],
      "print-00": [{"key": "artifacts/$PIPELINERUN/print-00/output_value.tgz", "name":
      "print-00-output_value", "path": "/tmp/outputs/output_value/data"}], "print-01":
      [{"key": "artifacts/$PIPELINERUN/print-01/output_value.tgz", "name": "print-01-output_value",
      "path": "/tmp/outputs/output_value/data"}], "print-10": [{"key": "artifacts/$PIPELINERUN/print-10/output_value.tgz",
      "name": "print-10-output_value", "path": "/tmp/outputs/output_value/data"}],
      "print-11": [{"key": "artifacts/$PIPELINERUN/print-11/output_value.tgz", "name":
      "print-11-output_value", "path": "/tmp/outputs/output_value/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"none": [["None", "$(results.None.path)"]], "none-2":
      [["None", "$(results.None.path)"]], "print-00": [["output_value", "$(results.output-value.path)"]],
      "print-01": [["output_value", "$(results.output-value.path)"]], "print-10":
      [["output_value", "$(results.output-value.path)"]], "print-11": [["output_value",
      "$(results.output-value.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"name": "any-sequencer in finally"}'
spec:
  pipelineSpec:
    tasks:
    - name: print-00
      taskSpec:
        steps:
        - name: main
          command:
          - sh
          - -c
          - |
            set -e
            echo $0 > $1
          - print-00
          - $(results.output-value.path)
          image: alpine:3.6
        results:
        - name: output-value
          type: string
          description: /tmp/outputs/output_value/data
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "print-00", "outputs":
              [{"description": "Represents an output paramter.", "name": "output_value",
              "type": "String"}], "version": "print-00@sha256=7c633686b0b637cfba6cba8c9b4e871cf172395432360d6aaa2d89623fb336b3"}'
            tekton.dev/template: ''
      timeout: 525600m
    - name: print-01
      taskSpec:
        steps:
        - name: main
          command:
          - sh
          - -c
          - |
            set -e
            echo $0 > $1
          - print-01
          - $(results.output-value.path)
          image: alpine:3.6
        results:
        - name: output-value
          type: string
          description: /tmp/outputs/output_value/data
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "print-01", "outputs":
              [{"description": "Represents an output paramter.", "name": "output_value",
              "type": "String"}], "version": "print-01@sha256=d511ac628d43cc5b393fbebd10be93662b30117f1413b84afd4e7b2e5ff5ed33"}'
            tekton.dev/template: ''
      timeout: 525600m
    - name: none
      taskSpec:
        steps:
        - name: main
          args:
          - --namespace
          - $(params.pipelineRun-namespace)
          - --prName
          - $(params.pipelineRun-name)
          - --taskList
          - print-00,print-01
          command:
          - any-task
          image: dspipelines/any-sequencer:latest
        - image: busybox
          name: copy-results
          command:
          - sh
          - -ec
          - |
            set -exo pipefail
            cp /tmp/outputs/None/data $(results.None.path);
        results:
        - name: None
          type: string
          description: /tmp/outputs/None/data
        stepTemplate:
          volumeMounts:
          - name: none
            mountPath: /tmp/outputs/None
        volumes:
        - name: none
          emptyDir: {}
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "None", "outputs":
              [{"description": "The output file to create the status", "name": "None"}],
              "version": "None@sha256=d85996d2400bd94ea45204590fcba9374edf952e060744ff0c5a5102f1318d7f"}'
            tekton.dev/template: ''
        params:
        - name: pipelineRun-name
        - name: pipelineRun-namespace
      timeout: 525600m
      params:
      - name: pipelineRun-name
        value: $(context.pipelineRun.name)
      - name: pipelineRun-namespace
        value: $(context.pipelineRun.namespace)
    finally:
    - name: any-sequencer-in-finally-24558-addon-group-1
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: Exception
        spec:
          pipelineSpec:
            params: []
            tasks:
            - name: print-10
              taskSpec:
                steps:
                - name: main
                  command:
                  - sh
                  - -c
                  - |
                    set -e
                    echo $0 > $1
                  - print-10
                  - $(results.output-value.path)
                  image: alpine:3.6
                results:
                - name: output-value
                  type: string
                  description: /tmp/outputs/output_value/data
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
                  annotations:
                    pipelines.kubeflow.org/component_spec_digest: '{"name": "print-10",
                      "outputs": [{"description": "Represents an output paramter.",
                      "name": "output_value", "type": "String"}], "version": "print-10@sha256=ea7fa8edfd92cf64a15f8464292143a4e0d5f34898368bfd63618884decf3be1"}'
                    tekton.dev/template: ''
              timeout: 525600m
            - name: print-11
              taskSpec:
                steps:
                - name: main
                  command:
                  - sh
                  - -c
                  - |
                    set -e
                    echo $0 > $1
                  - print-11
                  - $(results.output-value.path)
                  image: alpine:3.6
                results:
                - name: output-value
                  type: string
                  description: /tmp/outputs/output_value/data
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
                  annotations:
                    pipelines.kubeflow.org/component_spec_digest: '{"name": "print-11",
                      "outputs": [{"description": "Represents an output paramter.",
                      "name": "output_value", "type": "String"}], "version": "print-11@sha256=3b423bb0ced0bc21fb9157ce814a38c94d3e72718a33cfa8b4ef4f75abe725bd"}'
                    tekton.dev/template: ''
              timeout: 525600m
            - name: none-2
              taskSpec:
                steps:
                - name: main
                  args:
                  - --namespace
                  - $(context.pipelineRun.namespace)
                  - --prName
                  - $(context.pipelineRun.name)
                  - --taskList
                  - print-10,print-11
                  command:
                  - any-task
                  image: dspipelines/any-sequencer:latest
                - image: busybox
                  name: copy-results
                  command:
                  - sh
                  - -ec
                  - |
                    set -exo pipefail
                    cp /tmp/outputs/None/data $(results.None.path);
                results:
                - name: None
                  type: string
                  description: /tmp/outputs/None/data
                stepTemplate:
                  volumeMounts:
                  - name: none
                    mountPath: /tmp/outputs/None
                volumes:
                - name: none
                  emptyDir: {}
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
                  annotations:
                    pipelines.kubeflow.org/component_spec_digest: '{"name": "None",
                      "outputs": [{"description": "The output file to create the status",
                      "name": "None"}], "version": "None@sha256=aa59b9bee1939a20a127f07c0be2c186967560086207bc68a8d0401e03b63dcd"}'
                    tekton.dev/template: ''
              timeout: 525600m
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "false"
  timeout: 525600m
```

Note how any-sequencer outside of `finally` uses:
```yaml
- name: none
  taskSpec:
    steps:
    - name: main
      args:
      - --namespace
      - $(params.pipelineRun-namespace)
      - --prName
      - $(params.pipelineRun-name)
      - --taskList
      - print-00,print-01
      command:
      - any-task
      image: dspipelines/any-sequencer:latest
    (...)
    params:
    - name: pipelineRun-name
    - name: pipelineRun-namespace
  timeout: 525600m
  params:
  - name: pipelineRun-name
    value: $(context.pipelineRun.name)
  - name: pipelineRun-namespace
    value: $(context.pipelineRun.namespace)
```
i.e. passes `context.pipelineRun.name` and `context.pipelineRun.namespace` via params indirection.

However, the version inside of `finally` is:
```yaml
- name: none-2
  taskSpec:
    steps:
    - name: main
      args:
      - --namespace
      - $(context.pipelineRun.namespace)
      - --prName
      - $(context.pipelineRun.name)
      - --taskList
      - print-10,print-11
      command:
      - any-task
      image: dspipelines/any-sequencer:latest
    (...)
  timeout: 525600m
```
i.e. no indirection is happening.

Because of that, any-sequencer fails at runtime, as `$(context.pipelineRun.name)` and $`(context.pipelineRun.namespace)` do not resolved in the taskRun's step's `args`, only in its `params`.

**What did you expect to happen:**
For the two to work the same and generate the same code.

**Additional information:**
It seems that the `_handle_tekton_pipeline_variables` function only performs the Tekton variable substitution / indirection for tasks in `tasks` section, but not for the ones in `finally` section ([_tekton_handler.py, line 77](https://github.com/kubeflow/kfp-tekton/blob/8dbce394f48b104552455e104de3cbc10f6b89f5/sdk/python/kfp_tekton/compiler/_tekton_handler.py#L77)):
```python
def _handle_tekton_pipeline_variables(pipeline_run):
    """
    Handle tekton pipeline level variables, such as context.pipelineRun.name
    See more here https://github.com/tektoncd/pipeline/blob/master/docs/variables.md
    If there are tekton pipeline level variables in container, then
    1. Replease the $(context.pipeline/pipelineRun).*) to $(params.var_name)
       for example context.pipelineRun.name -> $(params.pipelineRun-name)
    2. Add $(context.pipeline/pipelineRun).*) to pipeline_run['spec']['pipelineSpec']['tasks']['params']
    3. Add $(context.pipeline/pipelineRun).*) to pipeline_run['spec']['pipelineSpec']['tasks']['taskSpec']['params']
    """

    pipeline_variables = {
        'pipeline-name': '$(context.pipeline.name)',
        'pipelineRun-name': '$(context.pipelineRun.name)',
        'pipelineRun-namespace': '$(context.pipelineRun.namespace)',
        'pipelineRun-uid': '$(context.pipelineRun.uid)'
    }

    add_type = pipeline_run.get('kind') != 'PipelineRun'
    task_list = pipeline_run['spec']['pipelineSpec']['tasks']  # <--- line 77
    for task in task_list:  # <--- only `tasks` is iterated over, but not `finally`
        if task.get('taskRef', {}):
            continue
        if 'taskSpec' in task and 'apiVersion' in task['taskSpec']:
            # recur for embedded pipeline resources
            if 'spec' in task['taskSpec'] and 'pipelineSpec' in task['taskSpec']['spec']:
                resource_spec = task['taskSpec']
                _handle_tekton_pipeline_variables(resource_spec)
            continue

        for key, val in pipeline_variables.items():
            task_str = json.dumps(task['taskSpec']['steps'])
            task_str = _process_argo_vars(task_str)
            if val in task_str:
                task_str = task_str.replace(val, '$(params.' + key + ')')
                task['taskSpec']['steps'] = json.loads(task_str)
                if task.get('params', ''):
                    if {'name': key, 'value': val} not in task['params']:
                        task['params'].append({'name': key, 'value': val})
                else:
                    task['params'] = [{'name': key, 'value': val}]

                found = False
                for param in task['taskSpec'].get('params', []):
                    if param['name'] == key:
                        found = True
                        break
                if not found:
                    param = {'name': key}
                    if add_type:
                        param['type'] = 'string'
                    task['taskSpec'].setdefault('params', []).append(param)

    return pipeline_run
````

**Environment:**

* Python Version (use `python --version`): 3.9.0
* SDK Version: 8bcb27213e1a6a0b75e133f2acb60e9be51827e5
* Tekton Version (use `tkn version`): 0.36.0
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
