### ISSUE TITLE
bug(sdk) Underscore miscompiling as hyphen in double-loop

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#1075]
/kind bug

**What steps did you take and what happened:**
1. Create a task producing an output with `_` (underscore) in its name.
2. Create a double nested loop (one loop inside of another).
3. Create an inner-most task consuming the output of the task from point 1.

```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import CEL_ConditionOp
from kfp_tekton.compiler import TektonCompiler

class Coder:
  def empty(self):
    return ""

TektonCompiler._get_unique_id_code = Coder.empty

def PrintOp(name: str, msg: str = None):
  if msg is None:
    msg = name
  print_op = load_component_from_text(
  """
  name: %s
  inputs:
  - {name: input_text, type: String, description: 'Represents an input parameter.'}
  outputs:
  - {name: output_value, type: String, description: 'Represents an output paramter.'}
  implementation:
    container:
      image: alpine:3.6
      command:
      - sh
      - -c
      - |
        set -e
        echo $0 > $1
      - {inputValue: input_text}
      - {outputPath: output_value}
  """ % (name)
  )
  return print_op(msg)

@dsl.pipeline("double_loop_with_underscore")
def double_loop_with_underscore(param_a: list = [1,2,3], param_b: list = ["a", "b", "c"]):
  op0 = PrintOp('print-0', f"Hello!")
  with dsl.ParallelFor(param_a):
    with dsl.ParallelFor(param_b):
      op1 = PrintOp('print-1', f"print {op0.output}")


if __name__ == '__main__':
  TektonCompiler().compile(double_loop_with_underscore, __file__.replace('.py', '.yaml'))
```

Getting:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: dap-26219
  annotations:
    tekton.dev/output_artifacts: '{"print-0": [{"key": "artifacts/$PIPELINERUN/print-0/output_value.tgz",
      "name": "print-0-output_value", "path": "/tmp/outputs/output_value/data"}],
      "print-1": [{"key": "artifacts/$PIPELINERUN/print-1/output_value.tgz", "name":
      "print-1-output_value", "path": "/tmp/outputs/output_value/data"}]}'
    tekton.dev/input_artifacts: '{"print-1": [{"name": "print-0-output_value", "parent_task":
      "print-0"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print-0": [["output_value", "$(results.output-value.path)"]],
      "print-1": [["output_value", "$(results.output-value.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "[1, 2, 3]", "name":
      "param_a", "optional": true, "type": "JsonArray"}, {"default": "[\"a\", \"b\",
      \"c\"]", "name": "param_b", "optional": true, "type": "JsonArray"}], "name":
      "dap_26219"}'
spec:
  params:
  - name: param_a
    value: '[1, 2, 3]'
  - name: param_b
    value: '["a", "b", "c"]'
  pipelineSpec:
    params:
    - name: param_a
      default: '[1, 2, 3]'
    - name: param_b
      default: '["a", "b", "c"]'
    tasks:
    - name: print-0
      taskSpec:
        steps:
        - name: main
          command:
          - sh
          - -c
          - |
            set -e
            echo $0 > $1
          - Hello!
          - $(results.output-value.path)
          image: alpine:3.6
        results:
        - name: output-value
          type: string
          description: /tmp/outputs/output_value/data
        metadata:
          labels:
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "print-0", "outputs":
              [{"description": "Represents an output paramter.", "name": "output_value",
              "type": "String"}], "version": "print-0@sha256=5dd3c506ec54281b82008ca8ec5d8142834eae18d74ce8a110a31dd6e371b40d"}'
      timeout: 525600m
    - runAfter:
      - print-0
      name: dap-26219-for-loop-1
      params:
      - name: param_a-loop-item
        value: $(params.param_a)
      - name: param_b
        value: $(params.param_b)
      - name: param_b-loop-item
        value: $(params.param_b)
      - name: print-0-output_value
        value: $(tasks.print-0.results.output-value)
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: param_a-loop-item
              type: string
            - name: param_b
              type: string
            - name: param_b-loop-item
              type: string
            - name: print-0-output_value
              type: string
            tasks:
            - name: dap-26219-for-loop-2
              params:
              - name: param_b-loop-item
                value: $(params.param_b-loop-item)
              - name: print-0-output_value
                value: $(params.print-0-output_value)
              taskSpec:
                apiVersion: custom.tekton.dev/v1alpha1
                kind: PipelineLoop
                spec:
                  pipelineSpec:
                    params:
                    - name: param_b-loop-item
                      type: string
                    - name: print-0-output_value
                      type: string
                    tasks:
                    - name: print-1
                      params:
                      - name: print-0-output_value
                        value: $(params.print-0-output-value)
                      taskSpec:
                        steps:
                        - name: main
                          command:
                          - sh
                          - -c
                          - |
                            set -e
                            echo $0 > $1
                          - print $(inputs.params.print-0-output_value)
                          - $(results.output-value.path)
                          image: alpine:3.6
                        params:
                        - name: print-0-output_value
                          type: string
                        results:
                        - name: output-value
                          type: string
                          description: /tmp/outputs/output_value/data
                        metadata:
                          labels:
                            pipelines.kubeflow.org/cache_enabled: "true"
                          annotations:
                            pipelines.kubeflow.org/component_spec_digest: '{"name":
                              "print-1", "outputs": [{"description": "Represents an
                              output paramter.", "name": "output_value", "type": "String"}],
                              "version": "print-1@sha256=3b81342bc143f625b58ebdb01e7c83b145880dee807be35c1e16fdb835d46580"}'
                      timeout: 525600m
                  iterateParam: param_b-loop-item
                metadata:
                  labels:
                    pipelines.kubeflow.org/cache_enabled: "true"
          iterateParam: param_a-loop-item
        metadata:
          labels:
            pipelines.kubeflow.org/cache_enabled: "true"
  timeouts:
    pipeline: 1051200m
    tasks: 525600m
```

Most notably:
```yaml
(...)
taskSpec:
  apiVersion: custom.tekton.dev/v1alpha1
  kind: PipelineLoop
  spec:
    pipelineSpec:
      params:
      - name: param_a-loop-item
        type: string
      - name: param_b
        type: string
      - name: param_b-loop-item
        type: string
      - name: print-0-output_value
        type: string
      tasks:
      - name: dap-26219-for-loop-2
        params:
        - name: param_b-loop-item
          value: $(params.param_b-loop-item)
        - name: print-0-output_value
          value: $(params.print-0-output_value)
        taskSpec:
          apiVersion: custom.tekton.dev/v1alpha1
          kind: PipelineLoop
          spec:
            pipelineSpec:
              params:
              - name: param_b-loop-item
                type: string
              - name: print-0-output_value
                type: string
              tasks:
              - name: print-1
                params:
                - name: print-0-output_value
                  value: $(params.print-0-output-value)
                (...)
```
Note: the PipelineLoop parameter is named `print-0-output_value`, while it's referred to as `$(params.print-0-output-value)`. Notably: `output_value` vs `output-value` (underscore vs hyphen).

That causes a validation error in Tekton.

**What did you expect to happen:**
For the reference to be `$(params.print-0-output_value)`, so that no validation error is triggered.

**Additional information:**
Notably, it works just fine for a single loop, only failing for a nested double-loop.

**Environment:**

* Python Version (use `python --version`): 3.9.0
* SDK Version: kfp-tekton-1.4.0
* Tekton Version (use `tkn version`): 0.36
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
