### ISSUE TITLE
bug(sdk) Loops: iterateParamPassStyle in wrong place in yaml

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#1086]
/kind bug

**What steps did you take and what happened:**
I used the test/example Python script, [loop_with_numeric.py](https://github.com/Tomcli/kfp-tekton/blob/d3a4d76aeb6eb70973eaadb95fd5c7dd055aabf9/sdk/python/tests/compiler/testdata/loop_with_numeric.py) with the newest version of kfp-tekton and no monkey-patching.

I got the yaml, just as in the repo:
```yaml
- name: my-pipeline-for-loop-2
  params:
  - name: from
    value: $(params.start)
  - name: my_pipe_param
    value: $(params.my_pipe_param)
  - name: to
    value: $(params.end)
  iterateParamPassStyle: inline
  taskSpec:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: PipelineLoop
    spec:
      pipelineSpec:
        params:
        - name: loop-item-param-1
          type: string
        - name: my_pipe_param
          type: string
        tasks: (...)
      iterateNumeric: loop-item-param-1
```
Notably, the part that actually gets passed to the controller is `taskSpec.spec`. In there, there is `iterateNumeric`. But `iterateParamPassStyle` is on the same level as `taskSpec`, so it is NOT passed to the controller. Because of that, the controller interprets `iterateParamPassStyle` to be empty.

It's not immediately visible in this case, because `"inline"` is the default value, so `""` and `"inline"` have the same result. But for the inner loop, it's much more obvious:
```yaml
- name: my-pipeline-for-loop-4
  params:
  - name: from
    value: '1'
  - name: my_pipe_param
    value: $(params.my_pipe_param)
  - name: to
    value: '2'
  itemPassStyle: file
  taskSpec:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: PipelineLoop
    spec:
      pipelineSpec:
        params:
        - name: loop-item-param-3
          type: string
        - name: my_pipe_param
          type: string
        tasks: (...)
      iterateNumeric: loop-item-param-3
```
Once again: `itemPassStyle` is on the same level as `taskSpec`, and not on the same level as `iterateNumeric`.

**What did you expect to happen:**
The generated yamls to be, respectively:
```yaml
- name: my-pipeline-for-loop-2
  params:
  - name: from
    value: $(params.start)
  - name: my_pipe_param
    value: $(params.my_pipe_param)
  - name: to
    value: $(params.end)
  taskSpec:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: PipelineLoop
    spec:
      pipelineSpec:
        params:
        - name: loop-item-param-1
          type: string
        - name: my_pipe_param
          type: string
        tasks: (...)
      iterateNumeric: loop-item-param-1
      iterateParamPassStyle: inline
```
and:
```yaml
- name: my-pipeline-for-loop-4
  params:
  - name: from
    value: '1'
  - name: my_pipe_param
    value: $(params.my_pipe_param)
  - name: to
    value: '2'
  taskSpec:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: PipelineLoop
    spec:
      pipelineSpec:
        params:
        - name: loop-item-param-3
          type: string
        - name: my_pipe_param
          type: string
        tasks: (...)
      iterateNumeric: loop-item-param-3
      itemPassStyle: file
```

They could use `extraFields` or `extra_fields` wrapper around those fields, but it's optional. We can handle both, really.

**Additional information:**
This problem was revealed when switching off our team's workaround (that was introduced while waiting for the public kfp-tekton solution to be implemented), that was as follows:

In `_group_to_dag_template` we used:
```python
if hasattr(sub_group, 'extra_fields') and sub_group.extra_fields is not None:
  extra_fields = cast(Mapping[str, Any], sub_group.extra_fields)
  for fname, fval in extra_fields.items():
      self.loops_pipeline[group_name]['spec'].setdefault('extra_fields', {})[fname] = fval
```

And in `_handle_tekton_custom_task` we had:
```python
for extra_field in custom_task[custom_task_key]['spec'].get('extra_fields') or []:
  custom_task_cr['spec'][extra_field] = custom_task[custom_task_key]['spec']['extra_fields'][extra_field]
if 'extra_fields' in custom_task[custom_task_key]['spec']:
  del custom_task[custom_task_key]['spec']['extra_fields']
```

The format for adding extra-fields was also a bit different (right now the class constructor simply includes such a field). After loop was created, we added:
```python
if iterate_param_pass_style is not None:
  loop_0.extra_fields['iterateParamPassStyle'] = iterate_param_pass_style
if item_pass_style is not None:
  loop_0.extra_fields['itemPassStyle'] = item_pass_style
```

Investigated it together with @bartlomiej-malecki from our team.

**Environment:**

* Python Version (use `python --version`): python 3.9
* SDK Version: 1a70d222f0edf880cea599a238605bf6d927b53b
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
