### ISSUE TITLE
Embedded status minimal doesn't work on new customRun

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#1154]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
With Tekton Embedded status minimal, the new customRun spec doesn't get populated as part of the kfp-tekton api. We need to update the kfp-tekton logic to handle with the new customRun package.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by Tomcli** [comment]
Deploy the latest Tekton with our latest release (V1 API, with customRun Pipeline loop). And apply the following feature flag
```shell
kubectl patch cm feature-flags -n tekton-pipelines -p '{"data":{"embedded-status":"minimal"}}'
```

Then run this test case in the ui, the pipeline is completed without any issue, but the status field is empty for the kfp-tekton api. For non looping pipelines we don't see this issue. This is very weird because even if the nested pipeline status is not populated, the root pipeline status should still be appear completed or running.

**Comment by yhwang** [comment]
hi @ScrapCodes I was running some pipeline flow with tekton 0.44 and found some weird information in the status of my pipelinerun:
```
status:
  childReferences:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    name: condition-rbxt6-flip-coin
    pipelineTaskName: flip-coin
    whenExpressions:
    - input: "false"
      operator: in
      values:
      - "false"
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    name: condition-rbxt6-flip-coin-2
    pipelineTaskName: flip-coin-2
    whenExpressions:
    - input: "false"
      operator: in
      values:
      - "false"
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    name: condition-rbxt6-print-msg
    pipelineTaskName: print-msg
    whenExpressions:
    - input: "false"
      operator: in
      values:
      - "false"
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    name: condition-rbxt6-print-msg-2
    pipelineTaskName: print-msg-2
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    name: condition-rbxt6-print-msg-3
    pipelineTaskName: print-msg-3
  - apiVersion: tekton.dev/v1alpha1
    kind: Run
    name: condition-rbxt6-flip-coin-2-driver
    pipelineTaskName: flip-coin-2-driver
  - apiVersion: tekton.dev/v1alpha1
    kind: Run
    name: condition-rbxt6-print-msg-2-driver
    pipelineTaskName: print-msg-2-driver
  - apiVersion: tekton.dev/v1alpha1
    kind: Run
    name: condition-rbxt6-print-msg-3-driver
    pipelineTaskName: print-msg-3-driver
  - apiVersion: tekton.dev/v1alpha1
    kind: Run
    name: condition-rbxt6-root-system-dag-driver
    pipelineTaskName: root-system-dag-driver
  - apiVersion: tekton.dev/v1alpha1
    kind: Run
    name: condition-rbxt6-condition-1-dag-driver
    pipelineTaskName: condition-1-dag-driver
  - apiVersion: tekton.dev/v1alpha1
    kind: Run
    name: condition-rbxt6-flip-coin-driver
    pipelineTaskName: flip-coin-driver
  - apiVersion: tekton.dev/v1alpha1
    kind: Run
    name: condition-rbxt6-print-msg-driver
    pipelineTaskName: print-msg-driver
  - apiVersion: tekton.dev/v1alpha1
    kind: Run
    name: condition-rbxt6-root-system-dag-pub-driver
    pipelineTaskName: root-system-dag-pub-driver
  - apiVersion: tekton.dev/v1alpha1
    kind: Run
    name: condition-rbxt6-condition-1-dag-pub-driver
    pipelineTaskName: condition-1-dag-pub-driver
```
For those `Run` tasks, they shall be `CustomRun`. Not sure if those incorrect `kind` information in childReference cause the logic in persistenceagent/pipelineloop fail to process the status information. This may be a bug in tekton. If this is the case, I believe you should fix it on tekton side first.
