### ISSUE TITLE
Generate PipelineRun with embedded pipelineSpec and taskSpec

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#143]
/kind feature

**Description:**
Convert the YAML produced by the `kfp-tekton` compiler:
- from multiple documents (`Condition`s, `Task`s, `Pipeline`, `PipelineRun`) into
- into a single `PipelineRun` with _embedded_  `pipelineSpec` and `taskSpec`s

This will simply the required work for down-stream integration with the KFP API and KFP UI.

**Additional information:**

```YAML
spec:
  pipelineSpec:
    tasks:
    - name: task1
      taskSpec:
        steps:
          ...
```
