### ISSUE TITLE
Rename Tekton task's main container as "main"

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#154]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]

Since Argo always name the main container as "main", it would be easier for the API to figure out which container to get the logs if we can change our compiler to rename all the main step in a task as "main". Argo did the container renaming in the execution level since Argo only allows one container as "main" and the rest are initContainer. Whereas Tekton only has the concept of steps but not initContainer. 

@ckadner what do you think?

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by ckadner** [comment]
@Tomcli -- can you add a few examples/snippets here?

**Comment by Tomcli** [comment]
e.g. right now we have this for one of our example task
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gcs-download
spec:
  params:
  - name: url
  steps:
  - args:
    - gsutil cat $0 | tee $1
    - $(inputs.params.url)
    - /tmp/results.txt
    command:
    - sh
    - -c
    image: google/cloud-sdk:216.0.0
    name: gcs-download
```

I want it to be this
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gcs-download
spec:
  params:
  - name: url
  steps:
  - args:
    - gsutil cat $0 | tee $1
    - $(inputs.params.url)
    - /tmp/results.txt
    command:
    - sh
    - -c
    image: google/cloud-sdk:216.0.0
    name: main
```
