### ISSUE TITLE
Enable passing output parameters as inputs for subsequent Tasks

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#19]
How do you pass parameter between each task? When trying to use KFP's parallel join example we get the following errors:
https://github.com/kubeflow/pipelines/blob/master/samples/core/parallel_join/parallel_join.py

Generated `pipeline.yaml`:
```YAML
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gcs-download
spec:
  inputs:
    params:
    - name: url1
  steps:
  - args:
    - gsutil cat $0 | tee $1
    - $(inputs.params.url1)
    - /tmp/results.txt
    command:
    - sh
    - -c
    image: google/cloud-sdk:279.0.0
    name: gcs-download
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gcs-download-2
spec:
  inputs:
    params:
    - name: url2
  steps:
  - args:
    - gsutil cat $0 | tee $1
    - $(inputs.params.url2)
    - /tmp/results.txt
    command:
    - sh
    - -c
    image: google/cloud-sdk:279.0.0
    name: gcs-download-2
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo
spec:
  inputs:
    params:
    - name: gcs-download-2-data
    - name: gcs-download-data
  steps:
  - args:
    - 'echo "Text 1: $0"; echo "Text 2: $1"'
    - $(inputs.params.gcs-download-data)
    - $(inputs.params.gcs-download-2-data)
    command:
    - sh
    - -c
    image: library/bash:4.4.23
    name: echo
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Download two messages
      in parallel and prints the concatenated result.", "inputs": [{"default": "gs://ml-pipeline-playground/shakespeare1.txt",
      "name": "url1", "optional": true}, {"default": "gs://ml-pipeline-playground/shakespeare2.txt",
      "name": "url2", "optional": true}], "name": "Parallel pipeline"}'
  name: parallel-pipeline
spec:
  params:
  - default: gs://ml-pipeline-playground/shakespeare1.txt
    name: url1
  - default: gs://ml-pipeline-playground/shakespeare2.txt
    name: url2
  tasks:
  - name: gcs-download
    params:
    - name: url1
      value: $(params.url1)
    taskRef:
      name: gcs-download
  - name: gcs-download-2
    params:
    - name: url2
      value: $(params.url2)
    taskRef:
      name: gcs-download-2
  - name: echo
    params:
    - name: gcs-download-2-data
      value: $(params.gcs-download-2-data)
    - name: gcs-download-data
      value: $(params.gcs-download-data)
    taskRef:
      name: echo
```

Console output:
```
$ kubectl apply -f pipeline.yaml
task.tekton.dev/gcs-download configured
task.tekton.dev/gcs-download-2 configured
task.tekton.dev/echo configured
Error from server (BadRequest): error when creating "pipeline.yaml": admission webhook "webhook.tekton.dev" denied the request: mutation failed: non-existent variable in "$(params.gcs-download-2-data)" for task parameter param[gcs-download-2-data]: pipelinespec.params.param[gcs-download-2-data]
```

_Originally posted by @Tomcli in https://github.com/kubeflow/kfp-tekton/pull/17#issuecomment-597899166_
