### ISSUE TITLE
Wanted Tekton feature: manageable artifacts

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#241]
/kind feature

**Description:**
Should Tekton have a more mature the concept of artifacts? There are concept of [Tekton artifacts](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#storage-resource) for the pipelineResource and workspaces. However, we don't see any plan for pipelineResource moving to v1beta1 and Tekton artifacts are not manageable on workspaces because they don't have REST api like S3. 

Also in the context of KFP, [KFP artifacts](https://www.kubeflow.org/docs/pipelines/overview/concepts/output-artifact/) need to be stored as tgz and tag with certain metadata. The Tekton pipelineResources/catalog tasks for uploading objects don't have the flexibility for injecting custom pre-processing code (e.g. wrap files into tgz, add metadata JSON file, etc).

We want the Tekton artifacts to able to support:
1. Custom pre-processing code before uploading objects, or options to bundle them into certain format. 
2. Ability to customize any S3 (including minio and non-regional endpoint) or other credentials when uploading those artifact objects no matter which namespace it's in.
3. Annotations/Labels on each task to distinguish output results vs output artifacts, also have annotations for each task to show who owns/generates the input artifacts previously.

**Comment by Tomcli** [comment]
Currently these features are done within our custom task and SDK annotation. Ideally we want these features come out of the box from Tekton

**Comment by drewbutlerbb4** [comment]
Currently, artifacts are not contained in the status of a PipelineRun. In order for the UI to display information about artifacts certain fields must be available describing these artifacts.

The way it is formatted in the Argo version of KFP is that `workflow.status.nodes[x].outputs.artifacts` is a list of artifacts where each artifact has the following information:
```
name: "mlpipeline-ui-metadata"
path: "/tmp/outputs/mlpipeline_ui_metadata/data"
s3:
{
  endpoint: "minio-service.kubeflow:9000"
  bucket: "mlpipeline"
  insecure: true
  accessKeySecret: {name: "mlpipeline-minio-artifact", key: "accesskey"}
  secretKeySecret: {name: "mlpipeline-minio-artifact", key: "secretkey"}
  key: "artifacts/calculation-pipeline-8bhr4/calculation-pipeline-8bhr4-2045269828/mlpipeline-ui-metadata.tgz"
}
optional: true
```
The ideal solution would be to have all this artifact information in some tekton workflow equivalent (`workflow.status.taskRuns[x].status.artifacts`?).

 Alternatively, I think we could get away with only holding the following information in the workflow.
```
name: "mlpipeline-ui-metadata"
bucket: "mlpipeline"
key: "artifacts/calculation-pipeline-8bhr4/calculation-pipeline-8bhr4-2045269828/mlpipeline-ui-metadata.tgz"
```
