### ISSUE TITLE
Tekton bug: Tekton task results not striping EOF new lines

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#273]
/kind bug

**What steps did you take and what happened:**
When passing Tekton output parameter using the Tekton task results feature, End of file new lines are not strip. It causes problem to users who may not aware of this limitation.

TODO tasks:
1. [x] Reproduce this bug using kfp-tekton
2. [x] Create issue on Tekton Pipelines
3. [x] Add tips and workaround until the bug is fixed.

**What did you expect to happen:**

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Comment by rafalbigaj** [comment]
@Tomcli it seems that there is an issue with `copy-artifacts` step. Please see the example of `PipelineRun` generated by `kfp-tekton` `TektonCompiler`:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Train the model and evaluate
      in notebook", "inputs": [{"name": "project_name", "type": "String"}, {"name":
      "notebook_name", "type": "String"}], "name": "Train the model and evaluate
      in notebook"}'
    tekton.dev/input_artifacts: '{"find-asset": [{"name": "find-project-project",
      "parent_task": "find-project"}], {"name": "find-project-project", "parent_task":
      "find-project"}]}'
    tekton.dev/output_artifacts: '{"find-project": [{"name": "find-project-project",
      "path": "/tmp/outputs/project/data"}]}'
  labels:
    pipelines.kubeflow.org/pipeline-sdk-type: kfp
  name: test-params-abf5
spec:
  params:
  - name: project_name
    value: 'a-project'
  - name: notebook_name
    value: 'a-notebook'
  pipelineSpec:
    params:
    - name: project_name
    - name: notebook_name
    tasks:
    - name: find-project
      params:
      - name: project_name
        value: $(params.project_name)
      taskSpec:
        params:
        - name: project_name
        results:
        - description: /tmp/outputs/project/data
          name: project
        steps:
        - command:
          - sh
          - -ex
          - -c
          - "echo \"$0\" > \"$1\""
          - $(inputs.params.project_name)
          - $(results.project.path)
          image: alpine:3.12
          name: main
        - env:
          - name: PIPELINERUN
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tekton.dev/pipelineRun']
          - name: PIPELINETASK
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tekton.dev/pipelineTask']
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: accesskey
                name: mlpipeline-minio-artifact
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: secretkey
                name: mlpipeline-minio-artifact
          image: minio/mc
          name: copy-artifacts
          script: '#!/usr/bin/env sh

            mc config host add storage http://minio-service.$NAMESPACE:9000 $AWS_ACCESS_KEY_ID
            $AWS_SECRET_ACCESS_KEY

            tar -cvzf project.tgz $(results.project.path)

            mc cp project.tgz storage/mlpipeline/artifacts/$PIPELINERUN/$PIPELINETASK/project.tgz

            '
    - name: find-asset
      params:
      - name: find-project-project
        value: $(tasks.find-project.results.project)
      - name: notebook_name
        value: $(params.notebook_name)
      taskSpec:
        params:
        - name: find-project-project
        - name: notebook_name
        steps:
        - command:
          - sh
          - -ex
          - -c
          - "echo \"'$0'\"\n echo \"'$1'\""
          - $(inputs.params.find-project-project)
          - $(inputs.params.notebook_name)
          image: alpine:3.12
          name: main
  podTemplate:
    imagePullSecrets:
    - name: ai-lifecycle
```

It's a very basic pipeline that in the first step "find-project" outputs the pipeline param "project_name" and then in the second step it prints the passed value from the former.

Here are the logs from the steps:

test-params-abf5-find-project-k48kx:
```
[main] + echo a-project
```

test-params-abf5-find-asset-dxwwl:
```
[main] 'a-project
[main] '
[main] 'a-notebook'
[main] + echo ''"'"'a-project
[main] '"'"
[main] + echo ''"'"'a-notebook'"'"
```

**Please see that "find-project-project" param value passed to the "find-asset" step is: "a-project\n".**

**Comment by Tomcli** [comment]
Thanks @rafalbigaj.

@ckadner I think the bug is with the value `$(tasks.find-project.results.project)` which it captured as part of Tekton Task results. Let's create a simpler version of this pipeline and see is Tekton willing to strip the EOF newlines.

**Comment by animeshsingh** [comment]
cc @afrittoli @pritidesai

**Comment by Tomcli** [comment]
here is a trimmed version of the tekton pipelinerun to reproduce this
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-params
spec:
  params:
  - name: project_name
    value: 'a-project'
  - name: notebook_name
    value: 'a-notebook'
  pipelineSpec:
    params:
    - name: project_name
    - name: notebook_name
    tasks:
    - name: find-project
      params:
      - name: project_name
        value: $(params.project_name)
      taskSpec:
        params:
        - name: project_name
        results:
        - description: /tmp/outputs/project/data
          name: project
        steps:
        - command:
          - sh
          - -ex
          - -c
          - "echo \"$0\" > \"$1\""
          - $(inputs.params.project_name)
          - $(results.project.path)
          image: alpine:3.12
          name: main
    - name: find-asset
      params:
      - name: find-project-project
        value: $(tasks.find-project.results.project)
      - name: notebook_name
        value: $(params.notebook_name)
      taskSpec:
        params:
        - name: find-project-project
        - name: notebook_name
        steps:
        - command:
          - sh
          - -ex
          - -c
          - "echo \"'$0'\"\n echo \"'$1'\""
          - $(inputs.params.find-project-project)
          - $(inputs.params.notebook_name)
          image: alpine:3.12
          name: main
```
