### ISSUE TITLE
dsl.Conditional not sanitising its PipelineParams

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#341]
/kind bug

**What steps did you take and what happened:**
If `dsl.Condition` uses outputs the names of which aren't already-sanitized, they aren't sanitised in the Tekton yaml either.

`coin.py` example with "output" replaced for "output_value" (sanitised as: "output-value"):
```python
import kfp
from kfp import dsl


def random_num_op(low, high):
    """Generate a random number between low and high."""
    return dsl.ContainerOp(
        name='Generate random number',
        image='python:alpine3.6',
        command=['sh', '-c'],
        arguments=['python -c "import random; print(random.randint($0, $1))" | tee $2', str(low), str(high), '/tmp/output'],
        file_outputs={'output_value': '/tmp/output_value'}
    )


def flip_coin_op():
    """Flip a coin and output heads or tails randomly."""
    return dsl.ContainerOp(
        name='Flip coin',
        image='python:alpine3.6',
        command=['sh', '-c'],
        arguments=['python -c "import random; result = \'heads\' if random.randint(0,1) == 0 '
                  'else \'tails\'; print(result)" | tee /tmp/output'],
        file_outputs={'output_value': '/tmp/output_value'}
    )


def print_op(msg):
    """Print a message."""
    return dsl.ContainerOp(
        name='Print',
        image='alpine:3.6',
        command=['echo', msg],
    )
    

@dsl.pipeline(
    name='Conditional execution pipeline',
    description='Shows how to use dsl.Condition().'
)
def flipcoin_pipeline():
    flip = flip_coin_op()
    with dsl.Condition(flip.output == 'heads'):
        random_num_head = random_num_op(0, 9)
        with dsl.Condition(random_num_head.output > 5):
            print_op('heads and %s > 5!' % random_num_head.output)
        with dsl.Condition(random_num_head.output <= 5):
            print_op('heads and %s <= 5!' % random_num_head.output)

    with dsl.Condition(flip.output == 'tails'):
        random_num_tail = random_num_op(10, 19)
        with dsl.Condition(random_num_tail.output > 15):
            print_op('tails and %s > 15!' % random_num_tail.output)
        with dsl.Condition(random_num_tail.output <= 15):
            print_op('tails and %s <= 15!' % random_num_tail.output)


if __name__ == '__main__':
    from kfp_tekton.compiler import TektonCompiler
    TektonCompiler().compile(flipcoin_pipeline, __file__.replace('.py', '.yaml'))
```

Resulting Tekton yaml:
```
      name: generate-random-number
      taskSpec:
        results:
        - description: /tmp/output_value
          name: output-value
        stepTemplate:
          volumeMounts:
          - mountPath: /tmp
            name: output-value
        steps:
        - args:
          - python -c "import random; print(random.randint($0, $1))" | tee $2
          - '0'
          - '9'
          - /tmp/output
          command:
          - sh
          - -c
          image: python:alpine3.6
          name: main
        - image: busybox
          name: copy-results
          script: '#!/bin/sh

            set -exo pipefail

            cp /tmp/output_value $(results.output-value.path);

            '
(...)
    - conditions:
      - conditionRef: super-condition
        params:
        - name: operand1
          value: $(tasks.generate-random-number.results.output_value)
        - name: operand2
          value: '5'
        - name: operator
          value: <=
      - conditionRef: super-condition
        params:
        - name: operand1
          value: $(tasks.flip-coin.results.output_value)
        - name: operand2
          value: heads
        - name: operator
          value: ==
      name: print-2
      params:
      - name: generate-random-number-output_value
        value: $(tasks.generate-random-number.results.output-value)
      taskSpec:
        params:
        - name: generate-random-number-output_value
        steps:
        - command:
          - echo
          - heads and $(inputs.params.generate-random-number-output_value) <= 5!
          image: alpine:3.6
          name: main
```

Note: for the same task, `print-2`, it's:
* in condition: `value: $(tasks.generate-random-number.results.output_value)`
* in params: `value: $(tasks.generate-random-number.results.output-value)`

**What did you expect to happen:**
`PipelineParam` in `dsl.Condition` should get sanitized just like any other `PipelineParam`.

**Additional information:**
It seems that the template of `PipelinePram` in `dsl.Condition` is created [in `_resolve_value_or_reference`](../blob/33493a23ea94472d41b5c995af76ddce69cc97a8/sdk/python/kfp_tekton/compiler/compiler.py#L164-L184):

```python
  def _resolve_value_or_reference(self, value_or_reference, potential_references):
    """_resolve_value_or_reference resolves values and PipelineParams, which could be task parameters or input parameters.
    Args:
      value_or_reference: value or reference to be resolved. It could be basic python types or PipelineParam
      potential_references(dict{str->str}): a dictionary of parameter names to task names
      """
    if isinstance(value_or_reference, dsl.PipelineParam):
      parameter_name = self._pipelineparam_full_name(value_or_reference)
      task_names = [task_name for param_name, task_name in potential_references if param_name == parameter_name]
      if task_names:
        task_name = task_names[0]
        # When the task_name is None, the parameter comes directly from ancient ancesters
        # instead of parents. Thus, it is resolved as the input parameter in the current group.
        if task_name is None:
          return '$(params.%s)' % parameter_name
        else:
          return '$(params.%s)' % task_name
      else:
        return '$(params.%s)' % parameter_name
    else:
      return str(value_or_reference)
```
^ the code above, however, does no sanitisation

To be precise, it IS sanitised, but with different mode, [in _sanitize_and_inject_artifact](../blob/33493a23ea94472d41b5c995af76ddce69cc97a8/sdk/python/kfp_tekton/compiler/compiler.py#L557-L569):

```python
  def _sanitize_and_inject_artifact(self, pipeline: dsl.Pipeline, pipeline_conf=None):
    """Sanitize operator/param names and inject pipeline artifact location."""

    # Sanitize operator names and param names
    sanitized_ops = {}

    for op in pipeline.ops.values():
      sanitized_name = sanitize_k8s_name(op.name)
      op.name = sanitized_name
      for param in op.outputs.values():
        param.name = sanitize_k8s_name(param.name, True)
        if param.op_name:
          param.op_name = sanitize_k8s_name(param.op_name)
```

For the task spec, the name is replaced [in `_data_passing_rewriter.py`](../blob/33493a23ea94472d41b5c995af76ddce69cc97a8/sdk/python/kfp_tekton/compiler/_data_passing_rewriter.py#L321-L339) too (it doesn't happen for the condition):
```python
    for template in container_templates + [pipeline_template]:
        spec = template.get('taskSpec', {}) or template.get('pipelineSpec', {})
        spec['results'] = [
            output_parameter for output_parameter in spec.get('results', [])
        ]
        # tekton results doesn't support underscore
        renamed_results_in_pipeline_task = set()
        for task_result in spec['results']:
            task_result_old_name = task_result.get('name')
            task_result_new_name = sanitize_k8s_name(task_result_old_name)
            if task_result_new_name != task_result_old_name:
                task_result['name'] = task_result_new_name
                renamed_results_in_pipeline_task.add(
                    (task_result_old_name, task_result_new_name))
        for renamed_result in renamed_results_in_pipeline_task:
            # Change results.downloaded_resultOutput to results.downloaded-resultoutput
            template['taskSpec'] = replace_big_data_placeholder(
                spec, 'results.%s' % renamed_result[0],
                'results.%s' % renamed_result[1])
```

It seems like at least one of these files should contain sanitisation for `dsl.Condition`, probably the latter.

Also: why do outputs get sanitised twice, with different rules/restrictions in `compiler.py` and `_data_passing_rewriter.py`? Wouldn't it be enough to sanitise them once, with the more restrictive of these rule sets?

**Environment:**

* SDK Version: 0.3.0
