### ISSUE TITLE
define script that you want to run for evaluating condition.

### ISSUE THREAD

**Issue by fenglixa** [kubeflow/kfp-tekton#353]
/kind feature

**Description:**

[A clear and concise description of what your proposal. What problem does it solve?]
to support the case of the condition with evaluating script, which already supported by Tekton:
https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/conditional-pipelinerun.yaml#L13-L15

Example as below:
```
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: file-exists
spec:
  params:
    - name: "path"
  resources:
    - name: workspace
      type: git
  check:
    image: alpine
    script: 'test -f $(resources.workspace.path)/$(params.path)'
```
