### ISSUE TITLE
The param dict json was not translate to yaml format

### ISSUE THREAD

**Issue by fenglixa** [kubeflow/kfp-tekton#430]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
compile sequential.py via newest kfp-tekton dsl code, the param dict json was not translate to yaml format, as below:
```
spec:
  params:
  - {name: url, value: 'gs://ml-pipeline-playground/shakespeare1.txt'}
  - {name: path, value: /tmp/results.txt}
```

The correct one should be as following:
```
spec:
  params:
  - name: url
    value: gs://ml-pipeline-playground/shakespeare1.txt
  - name: path
    value: /tmp/results.txt
```
Actually, all the python test script with params has the issue above.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):
