### ISSUE TITLE
Inner loop's iterated-on param not getting propagated to the outer loop

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#519]
/kind bug

**What steps did you take and what happened:**
Create a pipeline with two loops, where the inner one iterates over a pipeline parameter but doesn't use it in any other way.

```python
import kfp.dsl as dsl
from kfp_tekton.compiler import TektonCompiler
from typing import List


class Coder:
    def empty(self):
        return ""


TektonCompiler._get_unique_id_code = Coder.empty


@dsl.pipeline(name='my-pipeline')
def pipeline(my_pipe_param: List[int] = [100, 200, 300]):
    loop_args = [{'a': 1, 'b': 2}, {'a': 10, 'b': 20}]
    with dsl.ParallelFor(loop_args) as item:
        op1 = dsl.ContainerOp(
            name="my-in-coop1",
            image="library/bash:4.4.23",
            command=["sh", "-c"],
            arguments=["echo op1 %s" % (item.a)],
        )

        with dsl.ParallelFor(my_pipe_param) as inner_item:
            op11 = dsl.ContainerOp(
                name="my-inner-inner-coop",
                image="library/bash:4.4.23",
                command=["sh", "-c"],
                arguments=["echo op1 %s %s" % (item.a, inner_item)],
            )

        op2 = dsl.ContainerOp(
            name="my-in-coop2",
            image="library/bash:4.4.23",
            command=["sh", "-c"],
            arguments=["echo op2 %s" % item.b],
        )


if __name__ == '__main__':
    from kfp_tekton.compiler import TektonCompiler
    TektonCompiler().compile(pipeline, __file__.replace('.py', '.yaml'))
```

It generates the following, correct yaml for inner loop:
```
apiVersion: custom.tekton.dev/v1alpha1
kind: PipelineLoop
metadata: {name: for-loop-3}
spec:
  pipelineSpec:
    params:
    - {name: my_pipe_param-loop-item, type: string}
    - {name: loop-item-param-1-subvar-a, type: string}
    tasks:
    - name: my-inner-inner-coop
      params:
      - {name: loop-item-param-1-subvar-a, value: $(tasks.None.results.loop-item-param-1-subvar-a)}
      - {name: my_pipe_param-loop-item, value: $(params.my_pipe_param-loop-item)}
      taskSpec:
        steps:
        - name: main
          args: [echo op1 $(inputs.params.loop-item-param-1-subvar-a) $(inputs.params.my_pipe_param-loop-item)]
          command: [sh, -c]
          image: library/bash:4.4.23
        params:
        - {name: loop-item-param-1-subvar-a, type: string}
        - {name: my_pipe_param-loop-item, type: string}
      timeout: 0s
  iterateParam: my_pipe_param-loop-item
```
but for the outer loop:
```
apiVersion: custom.tekton.dev/v1alpha1
kind: PipelineLoop
metadata: {name: for-loop-2}
spec:
  pipelineSpec:
    params:
    - {name: loop-item-param-1, type: string}
    - {name: loop-item-param-1-subvar-a, type: string}
    - {name: loop-item-param-1-subvar-b, type: string}
    tasks:
    - name: my-in-coop1
      params:
      - {name: loop-item-param-1-subvar-a, value: $(tasks.None.results.loop-item-param-1-subvar-a)}
      taskSpec:
        steps:
        - name: main
          args: [echo op1 $(inputs.params.loop-item-param-1-subvar-a)]
          command: [sh, -c]
          image: library/bash:4.4.23
        params:
        - {name: loop-item-param-1-subvar-a, type: string}
      timeout: 0s
    - name: my-in-coop2
      params:
      - {name: loop-item-param-1-subvar-b, value: $(tasks.None.results.loop-item-param-1-subvar-b)}
      taskSpec:
        steps:
        - name: main
          args: [echo op2 $(inputs.params.loop-item-param-1-subvar-b)]
          command: [sh, -c]
          image: library/bash:4.4.23
        params:
        - {name: loop-item-param-1-subvar-b, type: string}
      timeout: 0s
    - name: for-loop-3
      taskRef: {apiVersion: custom.tekton.dev/v1alpha1, kind: PipelineLoop, name: for-loop-3}
      params:
      - {name: loop-item-param-1-subvar-a, value: $(params.loop-item-param-1-subvar-a)}
      - {name: my_pipe_param-loop-item, value: $(params.my_pipe_param)}
  iterateParam: loop-item-param-1
```
Note that `params.my_pipe_param` is used, but not passed in params, so a runtime error is produced:
````
cannot create resource with name = for-loop-3, gvk=custom.tekton.dev/v1alpha1, Kind=PipelineLoop:
admission webhook "validation.webhook.tektonextensions.custom.tekton.dev" denied the request:
validation failed: non-existent variable in "$(params.my_pipe_param)":
spec.pipelineSpec.tasks[2].params[my_pipe_param-loop-item]
```

**What did you expect to happen:**
For the parameter to be passed to the outer loop, which would prevent the runtime error from happening.


**Additional information:**
It may be that the input the loop is iterating on isn't counted as an input when propagating the params to the parent group?


**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):
