### ISSUE TITLE
CEL_ConditionOp: expressions with multiple pipelineparams miscompiles as if there was only one

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#527]
/kind bug

**What steps did you take and what happened:**
Create a pipeline using `CEL_ConditionOp` with expression using multiple pipeline params. Here is the simplest example:

```python
from kfp_tekton.tekton import CEL_ConditionOp
from kfp import dsl

@dsl.pipeline("main")
def main(a: int, b: int):
  CEL_ConditionOp(f"{a} == {b}")

if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  Compiler().compile(main, __file__.replace('.py', '.yaml'))
```

Generated yaml is:

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: main
  annotations:
    tekton.dev/output_artifacts: '{}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "a", "type": "Integer"},
      {"name": "b", "type": "Integer"}], "name": "main"}'
spec:
  params:
  - name: a
    value: ''
  - name: b
    value: ''
  pipelineSpec:
    params:
    - name: a
    - name: b
    tasks:
    - name: condition-cel
      params:
      - name: status
        value: $(params.a) == $(params.a)
      taskRef:
        name: cel_condition
        apiVersion: cel.tekton.dev/v1alpha1
        kind: CEL
  timeout: 0s
```

Note the: `$(params.a) == $(params.a)`, despite `f"{a} == {b}"` being used in DSL.

**What did you expect to happen:**

The parameters being compared, as in DSL:

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: main
  annotations:
    tekton.dev/output_artifacts: '{}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "a", "type": "Integer"},
      {"name": "b", "type": "Integer"}], "name": "main"}'
spec:
  params:
  - name: a
    value: ''
  - name: b
    value: ''
  pipelineSpec:
    params:
    - name: a
    - name: b
    tasks:
    - name: condition-cel
      params:
      - name: status
        value: $(params.a) == $(params.b)
      taskRef:
        name: cel_condition
        apiVersion: cel.tekton.dev/v1alpha1
        kind: CEL
  timeout: 0s
```

**Additional information:**

I checked that before Tekton variable substation, the expression looks like this:
```
$(inputs.params.a) == $(inputs.params.b)
```

So it looks like the problem happens on Argo --> Tekton variable substitution.

**Environment:**

* Python Version (use `python --version`): 3.9
* SDK Version: master's HEAD
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
