### ISSUE TITLE
Artefacts of nodes with long names miscompile

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#540]
/kind bug

**What steps did you take and what happened:**
Create a pipeline with an op which produces two outputs and uses their `outputPath`s. Parametrise that pipeline with the op's name length. Create instances for 20, 55, 80.

```python
from random import choice
from string import ascii_lowercase

from kfp import dsl
from kfp.components import load_component_from_text

def random_chars_of_len(length: int) -> str:
  return ''.join(
    (choice(ascii_lowercase) for i in range(length))
  )


def pipeline_for_len(op_name_length: int, op_name_base: str = ''):
  len_to_add = 0
  if len(op_name_base) < op_name_length:
    len_to_add = op_name_length - len(op_name_base)
  op_name_base += random_chars_of_len(len_to_add)

  op_name = op_name_base[:op_name_length]

  print(f"op_name = '{op_name}'")

  component_spec = f"""
    name: {op_name}
    inputs:
    - name: i
      type: Integer
    outputs:
    - name: incr_i
      type: Integer
    - name: sq_i
      type: Integer
    implementation:
      container:
        image: sth
        command:
        - whatever
        - outputPath: sq_i
        - outputPath: incr_i
  """

  op = load_component_from_text(component_spec)

  @dsl.pipeline("main-pipeline")
  def main_pipeline(i: int):
    op(i)
    #op1 = op(op0.outputs['incr_i'])
  return main_pipeline

def main():
  from kfp_tekton.compiler import TektonCompiler as Compiler
  lengths = [20, 55, 80]
  max_length = max(lengths)
  op_name_base = random_chars_of_len(max_length)

  for length in lengths:
    main_pipeline = pipeline_for_len(length, op_name_base)
    fname = __file__.replace('.py', f'-{length}.yaml')
    Compiler().compile(main_pipeline, fname)

if __name__ == '__main__':
  main()
```

The "20" file looks correct:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: main-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"iqbseygiodndxswmwvap": [{"key": "artifacts/$PIPELINERUN/iqbseygiodndxswmwvap/incr_i.tgz",
      "name": "iqbseygiodndxswmwvap-incr_i", "path": "/tmp/outputs/incr_i/data"},
      {"key": "artifacts/$PIPELINERUN/iqbseygiodndxswmwvap/sq_i.tgz", "name": "iqbseygiodndxswmwvap-sq_i",
      "path": "/tmp/outputs/sq_i/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"iqbseygiodndxswmwvap": [["incr_i", "$(results.incr-i.path)"],
      ["sq_i", "$(results.sq-i.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "i", "type": "Integer"}],
      "name": "main-pipeline"}'
spec:
  params:
  - name: i
    value: ''
  pipelineSpec:
    params:
    - name: i
    tasks:
    - name: iqbseygiodndxswmwvap
      taskSpec:
        steps:
        - name: main
          command:
          - whatever
          - $(results.sq-i.path)
          - $(results.incr-i.path)
          image: sth
        results:
        - name: sq-i
          description: /tmp/outputs/sq_i/data
        - name: incr-i
          description: /tmp/outputs/incr_i/data
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
              {"command": ["whatever", {"outputPath": "sq_i"}, {"outputPath": "incr_i"}],
              "image": "sth"}}, "inputs": [{"name": "i", "type": "Integer"}], "name":
              "iqbseygiodndxswmwvap", "outputs": [{"name": "incr_i", "type": "Integer"},
              {"name": "sq_i", "type": "Integer"}]}'
            tekton.dev/template: ''
      timeout: 0s
  timeout: 0s
```

Meanwhile, "50" and "80" variants differs vastly from it:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: main-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq":
      [{"key": "artifacts/$PIPELINERUN/kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq/incr_i.tgz",
      "name": "kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-incr_i", "path":
      "/tmp/outputs/incr_i/data"}, {"key": "artifacts/$PIPELINERUN/kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq/sq_i.tgz",
      "name": "kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-sq_i", "path":
      "/tmp/outputs/sq_i/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq":
      [["kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-incr_i", "/tmp/outputs/incr_i/data"],
      ["kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-sq_i", "/tmp/outputs/sq_i/data"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "i", "type": "Integer"}],
      "name": "main-pipeline"}'
spec:
  params:
  - name: i
    value: ''
  pipelineSpec:
    params:
    - name: i
    tasks:
    - name: kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq
      taskSpec:
        steps:
        - name: main
          command:
          - whatever
          - $(results.sq-i.path)
          - $(results.incr-i.path)
          image: sth
        results:
        - name: sq-i
          description: /tmp/outputs/sq_i/data
        - name: incr-i
          description: /tmp/outputs/incr_i/data
        stepTemplate:
          volumeMounts:
          - name: kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-i
            mountPath: /tmp/outputs/incr_i
          - name: kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-s
            mountPath: /tmp/outputs/sq_i
        volumes:
        - name: kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-i
          emptyDir: {}
        - name: kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-s
          emptyDir: {}
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
              {"command": ["whatever", {"outputPath": "sq_i"}, {"outputPath": "incr_i"}],
              "image": "sth"}}, "inputs": [{"name": "i", "type": "Integer"}], "name":
              "kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq", "outputs":
              [{"name": "incr_i", "type": "Integer"}, {"name": "sq_i", "type": "Integer"}]}'
            tekton.dev/template: ''
      timeout: 0s
  timeout: 0s
```

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: main-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng":
      [{"key": "artifacts/$PIPELINERUN/iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng/incr_i.tgz",
      "name": "iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng-incr_i",
      "path": "/tmp/outputs/incr_i/data"}, {"key": "artifacts/$PIPELINERUN/iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng/sq_i.tgz",
      "name": "iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng-sq_i", "path":
      "/tmp/outputs/sq_i/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng":
      [["iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng-incr_i", "/tmp/outputs/incr_i/data"],
      ["iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng-sq_i", "/tmp/outputs/sq_i/data"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "i", "type": "Integer"}],
      "name": "main-pipeline"}'
spec:
  params:
  - name: i
    value: ''
  pipelineSpec:
    params:
    - name: i
    tasks:
    - name: iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng
      taskSpec:
        steps:
        - name: main
          command:
          - whatever
          - $(results.sq-i.path)
          - $(results.incr-i.path)
          image: sth
        results:
        - name: sq-i
          description: /tmp/outputs/sq_i/data
        - name: incr-i
          description: /tmp/outputs/incr_i/data
        stepTemplate:
          volumeMounts:
          - name: iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng
            mountPath: /tmp/outputs/incr_i
          - name: iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng
            mountPath: /tmp/outputs/sq_i
        volumes:
        - name: iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng
          emptyDir: {}
        - name: iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng
          emptyDir: {}
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
              {"command": ["whatever", {"outputPath": "sq_i"}, {"outputPath": "incr_i"}],
              "image": "sth"}}, "inputs": [{"name": "i", "type": "Integer"}], "name":
              "iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqngvjzzasadorzbmyyruufsyhu",
              "outputs": [{"name": "incr_i", "type": "Integer"}, {"name": "sq_i",
              "type": "Integer"}]}'
            tekton.dev/template: ''
      timeout: 0s
  timeout: 0s
```

Not only does it provide an additional `stepTemplate` field with `volumeMount` for the outputs, but that `stepTemplate` lost the tail of `{op_name}-{output_name}`), which in case of "80" is actually the whole of output name (!):
```
stepTemplate:
  volumeMounts:
  - name: kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-i
    mountPath: /tmp/outputs/incr_i
  - name: kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-s
    mountPath: /tmp/outputs/sq_i
```
```
stepTemplate:
  volumeMounts:
  - name: iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng
    mountPath: /tmp/outputs/incr_i
  - name: iqbseygiodndxswmwvapqkgfawmqrxdobtrbpgyhsueglopqfangfqqng
    mountPath: /tmp/outputs/sq_i
```

However, in `tekton.dev/output_artifacts` and `tekton.dev/artifact_items` annotation, the names are correct --- and therefore different:
```
metadata:
  name: main-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq":
      [{"key": "artifacts/$PIPELINERUN/kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq/incr_i.tgz",
      "name": "kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-incr_i", "path":
      "/tmp/outputs/incr_i/data"}, {"key": "artifacts/$PIPELINERUN/kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq/sq_i.tgz",
      "name": "kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-sq_i", "path":
      "/tmp/outputs/sq_i/data"}]}'
    tekton.dev/artifact_items: '{"kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq":
      [["kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-incr_i", "/tmp/outputs/incr_i/data"],
      ["kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbq-sq_i", "/tmp/outputs/sq_i/data"]]}'
```
```
metadata:
  name: main-pipeline
  annotations:
    tekton.dev/output_artifacts: '{"kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbqqo":
      [{"key": "artifacts/$PIPELINERUN/kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbqqo/incr_i.tgz",
      "name": "kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbqqo-incr_i",
      "path": "/tmp/outputs/incr_i/data"}, {"key": "artifacts/$PIPELINERUN/kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbqqo/sq_i.tgz",
      "name": "kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbqqo-sq_i", "path":
      "/tmp/outputs/sq_i/data"}]}'
    tekton.dev/artifact_items: '{"kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbqqo":
      [["kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbqqo-incr_i", "/tmp/outputs/incr_i/data"],
      ["kbzikssuficlrrvryvtvbjbdalluoofnlockfakkfsybnayjymfizbqqo-sq_i", "/tmp/outputs/sq_i/data"]]}'
```

Note how both the op's name and the combined "{op_name}-{output_name}" are capped at length 57.

**What did you expect to happen:**

No `stepTemplate` for either of examples.

**Additional information:**
The problem seems to lie in sanitisation of "{op_name}-{output_name}", which --- by default --- cap it at the same length as the op_name (which is 57). That string, however, is compared to its full form elsewhere:

[_op_to_template.py, lines 258-261](https://github.com/kubeflow/kfp-tekton/blob/24c2e5bcacd75638d9ff7c3478ccee15cbd889a8/sdk/python/kfp_tekton/compiler/_op_to_template.py#L258-L261):
```python
# Record what artifacts are moved to result parameters.
parameter_name = sanitize_k8s_name(processed_op.name + '-' + name, allow_capital_underscore=True)
replaced_param_list.append(parameter_name)
artifact_to_result_mapping[parameter_name] = name
```

[_op_to_template.py, lines 292-302](https://github.com/kubeflow/kfp-tekton/blob/24c2e5bcacd75638d9ff7c3478ccee15cbd889a8/sdk/python/kfp_tekton/compiler/_op_to_template.py#L292-L302):
```python
artifact_name = artifact_to_result_mapping.get(artifact['name'], artifact['name'])
if artifact['name'] in replaced_param_list:
    artifact_items.append([artifact_name, "$(results.%s.path)" % sanitize_k8s_name(artifact_name)])
else:
    artifact_items.append([artifact_name, artifact['path']])
    if artifact['path'].rsplit("/", 1)[0] not in mounted_artifact_paths:
        if artifact['path'].rsplit("/", 1)[0] == "":
            raise ValueError('Undefined volume path or "/" path artifacts are not allowed.')
        volume_mount_step_template.append({
            'name': sanitize_k8s_name(artifact['name']), 'mountPath': artifact['path'].rsplit("/", 1)[0]
        })
```

[_k8s_helper.py, lines 20-25](https://github.com/kubeflow/kfp-tekton/blob/24c2e5bcacd75638d9ff7c3478ccee15cbd889a8/sdk/python/kfp_tekton/compiler/_k8s_helper.py#L20-L25):
```
def sanitize_k8s_name(name,
                      allow_capital_underscore=False,
                      allow_dot=False,
                      allow_slash=False,
                      max_length=57,
                      suffix_space=0):
  ...
```

As can be seen, sanitisation not only will cap the whole artifact name at 57 and not treating the "-{output_name}" part as a suffix, but also `artifact['name']` is only getting sanitised later on, AFTER the check in that mapping. So if the sanitisation changes that name in any way, it won't be found.

Solutions can include removing the cap in this call (by setting `max_length=Float('Inf')`) and sanitising `artifact['name']` right away with the very same call.

**Environment:**

* Python Version (use `python --version`): 3.9
* SDK Version: current master's HEAD ([24c2e5bcacd75638d9ff7c3478ccee15cbd889a8](https://github.com/kubeflow/kfp-tekton/commit/24c2e5bcacd75638d9ff7c3478ccee15cbd889a8))
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
