### ISSUE TITLE
Custom task condition doesn't generate status result in some cases

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#546]
/kind bug

**What steps did you take and what happened:**
The below example doesn't generate the condition status for the first custom task.

```
from kfp import dsl
from kfp_tekton.tekton import CEL_ConditionOp


@dsl.pipeline("example-ab")
def example_ab(num: int = 42):
  isNumZero = CEL_ConditionOp(f"{num} == 0").output
  zero = CEL_ConditionOp(f"0").output

@dsl.pipeline("example-ba")
def example_ba(num: int = 42):
  zero = CEL_ConditionOp(f"0").output
  isNumZero = CEL_ConditionOp(f"{num} == 0").output

def main():
  from kfp_tekton.compiler import TektonCompiler as Compiler
  Compiler().compile(example_ab, __file__.replace('.py', '-ab.yaml'))
  Compiler().compile(example_ba, __file__.replace('.py', '-ba.yaml'))

if __name__ == '__main__':
  main()
```

outputs: Note that the first cel-condition custom task didn't generate the condition statement as status.
```
spec:
  params:
  - name: num
    value: '42'
  pipelineSpec:
    params:
    - name: num
      default: '42'
    tasks:
    - name: cel-condition
      taskRef:
        name: cel_condition
        apiVersion: cel.tekton.dev/v1alpha1
        kind: CEL
    - name: cel-condition-2
      params:
      - name: status
        value: $(params.num) == 0
      taskRef:
        name: cel_condition
        apiVersion: cel.tekton.dev/v1alpha1
        kind: CEL
  timeout: 0s
```

**What did you expect to happen:**

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):
