### ISSUE TITLE
Tekton variables for custom task results are not sanitized when using it in condition

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#577]
/kind bug

**What steps did you take and what happened:**
When defining custom task output as `return_value` (with underscore), we need to sanitize it in to hyphen `-` order to let the Tekton controller understands what to do. These variables are already sanitized for regular tasks I/O, but the below edge case wasn't sanitized within custom task.
```
- name: condition-cel
      params:
      - name: status
        value: $(tasks.node-run-bash-script.results.return_value) == 0
```

We need to update the compiler to cover this edge case.

**What did you expect to happen:**

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):
