### ISSUE TITLE
dsl.ParallelFor getting wrong results for list of non-dict objects

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#656]
/kind bug

**What steps did you take and what happened:**

```python
from kfp import dsl


class PrintOp(dsl.ContainerOp):
    def __init__(self, name: str, msg: str):
        super(PrintOp, self).__init__(
            name=name,
            image='alpine:3.6',
            command=['echo', msg, ">", "/tmp/stdout"],
            file_outputs={"stdout": "/tmp/stdout"}
        )

def main():
    with dsl.ParallelFor([{"a": "A", "b": "B"}, {"a": 0, "b": 1}]):
      PrintOp("success", msg="It does work")
    with dsl.ParallelFor(["a", "b"]):
      PrintOp("failure", msg="It doesn't work")

if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  Compiler().compile(main, __file__.replace('.py', '.yaml'))
```

results in:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: main
  annotations:
    tekton.dev/output_artifacts: '{"failure": [{"key": "artifacts/$PIPELINERUN/failure/stdout.tgz",
      "name": "failure-stdout", "path": "/tmp/stdout"}], "success": [{"key": "artifacts/$PIPELINERUN/success/stdout.tgz",
      "name": "success-stdout", "path": "/tmp/stdout"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"failure": [["stdout", "$(results.stdout.path)"]],
      "success": [["stdout", "$(results.stdout.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"name": "Main"}'
spec:
  pipelineSpec:
    tasks:
    - name: main-71f66-for-loop-2
      params:
      - name: loop-item-param-1
        value: '[{"a": "A", "b": "B"}, {"a": 0, "b": 1}]'
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: loop-item-param-1-subvar-a
              type: string
            - name: loop-item-param-1-subvar-b
              type: string
            tasks:
            - name: success
              taskSpec:
                steps:
                - name: main
                  command:
                  - echo
                  - It does work
                  - '>'
                  - $(results.stdout.path)
                  image: alpine:3.6
                results:
                - name: stdout
                  description: /tmp/stdout
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
                  annotations:
                    tekton.dev/template: ''
              timeout: 0s
          iterateParam: loop-item-param-1
    - name: main-71f66-for-loop-4
      params:
      - name: loop-item-param-3
        value: '[''a'', ''b'']'
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: loop-item-param-3
              type: string
            tasks:
            - name: failure
              taskSpec:
                steps:
                - name: main
                  command:
                  - echo
                  - It doesn't work
                  - '>'
                  - $(results.stdout.path)
                  image: alpine:3.6
                results:
                - name: stdout
                  description: /tmp/stdout
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
                  annotations:
                    tekton.dev/template: ''
              timeout: 0s
          iterateParam: loop-item-param-3
  timeout: 0s
```
Note the correct:
```yaml
value: '[{"a": "A", "b": "B"}, {"a": 0, "b": 1}]'
```
but incorrect:
```yaml
value: '[''a'', ''b'']'
```

**What did you expect to happen:**
Any (trivially?) jsonifiable types should be supported by `dsl.ParallelFor`.

**Additional information:**
It looks like python-stringifying, instead of json-dumping, the argument if the first element is not a dictionary, in [HEAD's compiler.py](https://github.com/kubeflow/kfp-tekton/blob/77963c3ceaf042bba1278797c349fe83dc79701b/sdk/python/kfp_tekton/compiler/compiler.py#L366-L374):
```python
if isinstance(loop_arg_value[0], dict):
  for argument_set in loop_arg_value:
    c_dict = {}
    for k, v in argument_set.items():
      c_dict[sanitize_k8s_name(k, True)] = v
    sanitized_tasks.append(c_dict)
  loop_args_str_value = json.dumps(sanitized_tasks, sort_keys=True)
else:
  loop_args_str_value = str(loop_arg_value)
```
Note how for dicts, `json.dumps` is used, but `str` for other cases. In case of e.g. integers it makes no difference, but for strings, python-stringification uses `'`, while jsonification uses `"`.

**Environment:**

* Python Version (use `python --version`): 3.9.0
* SDK Version: master's HEAD 77963c3ceaf042bba1278797c349fe83dc79701b
