### ISSUE TITLE
Recursion is not generating a resource, but uses it anyway

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#683]
/kind bug

**What steps did you take and what happened:**
Created a pipeline which uses a recursive graph component. Compiled.

```python
from kfp import dsl
from kfp_tekton.tekton import CEL_ConditionOp


class CelCondition(dsl.Condition):
  def __init__(self, pred: str, name: str = None):
    super().__init__(CEL_ConditionOp(pred).output == 'true', name)

class PrintOp(dsl.ContainerOp):
    def __init__(self, name: str, msg: str):
        super(PrintOp, self).__init__(
            name=name,
            image='alpine:3.6',
            command=['echo', msg, ">", "/tmp/stdout"],
            file_outputs={"stdout": "/tmp/stdout"}
        )

@dsl.graph_component
def recur(i: int):
  decr_i = CEL_ConditionOp(f"{i} - 1").output
  PrintOp("print-iter", f"Iter: {decr_i}")
  with dsl.Condition(decr_i != 0):
    recur(decr_i)

@dsl.pipeline("recur-and-condition")
def recur_and_condition(iter_num: int = 42):
  recur(iter_num)


if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  Compiler().compile(recur_and_condition, __file__.replace('.py', '-default.yaml'))

  from kfp_tekton.compiler import TektonCompiler as Compiler
  from kfp_tekton.compiler.pipeline_utils import TektonPipelineConf
  tekton_pipeline_conf = TektonPipelineConf()
  tekton_pipeline_conf.set_tekton_inline_spec(False)
  Compiler().compile(recur_and_condition, __file__.replace('.py', '-false.yaml'), tekton_pipeline_conf=tekton_pipeline_conf)
```

Both compilations produced only one file, identical between the calls:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: recur-and-condition
  annotations:
    tekton.dev/output_artifacts: '{"print-iter": [{"key": "artifacts/$PIPELINERUN/print-iter/stdout.tgz",
      "name": "print-iter-stdout", "path": "/tmp/stdout"}]}'
    tekton.dev/input_artifacts: '{"print-iter": [{"name": "condition-cel-outcome",
      "parent_task": "condition-cel"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print-iter": [["stdout", "$(results.stdout.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "42", "name": "iter_num",
      "optional": true, "type": "Integer"}], "name": "recur-and-condition"}'
    tekton.dev/resource_templates: '[{"apiVersion": "custom.tekton.dev/v1alpha1",
      "kind": "PipelineLoop", "metadata": {"name": "recur-and-condition-c901d-graph-recur-1"},
      "spec": {"iterateParam": "just_one_iteration", "pipelineSpec": {"params": [{"name":
      "iter_num", "type": "string"}, {"name": "just_one_iteration", "type": "string"}],
      "tasks": [{"name": "condition-cel", "params": [{"name": "outcome", "value":
      "$(params.iter_num) - 1"}], "taskRef": {"apiVersion": "cel.tekton.dev/v1alpha1",
      "kind": "CEL", "name": "cel_condition"}}, {"name": "print-iter", "params": [{"name":
      "condition-cel-outcome", "value": "$(tasks.condition-cel.results.outcome)"}],
      "taskSpec": {"metadata": {"annotations": {"tekton.dev/template": ""}, "labels":
      {"pipelines.kubeflow.org/cache_enabled": "true", "pipelines.kubeflow.org/generation":
      "", "pipelines.kubeflow.org/pipelinename": ""}}, "params": [{"name": "condition-cel-outcome",
      "type": "string"}], "results": [{"description": "/tmp/stdout", "name": "stdout"}],
      "steps": [{"command": ["echo", "Iter: $(inputs.params.condition-cel-outcome)",
      ">", "$(results.stdout.path)"], "image": "alpine:3.6", "name": "main"}]}, "timeout":
      "0s"}, {"name": "recur", "params": [{"name": "iter_num", "value": "$(tasks.condition-cel.results.outcome)"},
      {"name": "just_one_iteration", "value": ["1"]}], "taskRef": {"apiVersion": "custom.tekton.dev/v1alpha1",
      "kind": "PipelineLoop", "name": "recur-and-condition-c901d-graph-recur-1"},
      "when": [{"input": "$(tasks.condition-cel.results.outcome)", "operator": "notin",
      "values": ["0"]}]}]}}}]'
spec:
  params:
  - name: iter_num
    value: '42'
  pipelineSpec:
    params:
    - name: iter_num
      default: '42'
    tasks:
    - name: recur-and-condition-c901d-graph-recur-1
      taskRef:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        name: recur-and-condition-c901d-graph-recur-1
      params:
      - name: iter_num
        value: $(params.iter_num)
      - name: just_one_iteration
        value:
        - '1'
  timeout: 0s
```

Note how "recur-and-condition-c901d-graph-recur-1" is referenced but not created as a resource.

**What did you expect to happen:**
I would expect the referenced resource to actually be created, in both cases.

It looks like a regression to me.

**Additional information:**
What's interesting is how it seems that the below example only differs in lengths of names of functions, and yet looks very different (although wrong too), as it seems that at least the `.set_tekton_inline_spec(False)` part did SOMETHING:

```python
from kfp import dsl
from kfp_tekton.tekton import CEL_ConditionOp


class CelCondition(dsl.Condition):
  def __init__(self, pred: str, name: str = None):
    super().__init__(CEL_ConditionOp(pred).output == 'true', name)

class PrintOp(dsl.ContainerOp):
    def __init__(self, name: str, msg: str):
        super(PrintOp, self).__init__(
            name=name,
            image='alpine:3.6',
            command=['echo', msg, ">", "/tmp/stdout"],
            file_outputs={"stdout": "/tmp/stdout"}
        )

@dsl.graph_component
def function_the_name_of_which_is_exactly_51_chars_long(i: int):
  decr_i = CEL_ConditionOp(f"{i} - 1").output
  PrintOp("print-iter", f"Iter: {decr_i}")
  with dsl.Condition(decr_i != 0):
    function_the_name_of_which_is_exactly_51_chars_long(decr_i)

@dsl.pipeline("pipeline the name of which is exactly 51 chars long")
def pipeline_the_name_of_which_is_exactly_51_chars_long(iter_num: int = 42):
  function_the_name_of_which_is_exactly_51_chars_long(iter_num)


if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  Compiler().compile(pipeline_the_name_of_which_is_exactly_51_chars_long, __file__.replace('.py', '-default.yaml'))

  from kfp_tekton.compiler import TektonCompiler as Compiler
  from kfp_tekton.compiler.pipeline_utils import TektonPipelineConf
  tekton_pipeline_conf = TektonPipelineConf()
  tekton_pipeline_conf.set_tekton_inline_spec(False)
  Compiler().compile(pipeline_the_name_of_which_is_exactly_51_chars_long, __file__.replace('.py', '-false.yaml'), tekton_pipeline_conf=tekton_pipeline_conf)
```

long_names-default.yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-the-name-of-which-is-exactly-51-chars-long
  annotations:
    tekton.dev/output_artifacts: '{"print-iter": [{"key": "artifacts/$PIPELINERUN/print-iter/stdout.tgz",
      "name": "print-iter-stdout", "path": "/tmp/stdout"}]}'
    tekton.dev/input_artifacts: '{"print-iter": [{"name": "condition-cel-outcome",
      "parent_task": "condition-cel"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print-iter": [["stdout", "$(results.stdout.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "42", "name": "iter_num",
      "optional": true, "type": "Integer"}], "name": "pipeline the name of which is
      exactly 51 chars long"}'
spec:
  params:
  - name: iter_num
    value: '42'
  pipelineSpec:
    params:
    - name: iter_num
      default: '42'
    tasks:
    - name: pipeline-the-name-of-which-is-exactly-51-cha-b3de4-graph-function-the-name-of-which-is-exactly-51-chars-long
      params:
      - name: iter_num
        value: $(params.iter_num)
      - name: just_one_iteration
        value:
        - '1'
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: iter_num
              type: string
            - name: just_one_iteration
              type: string
            tasks:
            - name: condition-cel
              params:
              - name: outcome
                value: $(params.iter_num) - 1
              taskRef:
                name: cel_condition
                apiVersion: cel.tekton.dev/v1alpha1
                kind: CEL
            - name: print-iter
              params:
              - name: condition-cel-outcome
                value: $(tasks.condition-cel.results.outcome)
              taskSpec:
                steps:
                - name: main
                  command:
                  - echo
                  - 'Iter: $(inputs.params.condition-cel-outcome)'
                  - '>'
                  - $(results.stdout.path)
                  image: alpine:3.6
                params:
                - name: condition-cel-outcome
                  type: string
                results:
                - name: stdout
                  description: /tmp/stdout
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
                  annotations:
                    tekton.dev/template: ''
              timeout: 0s
            - name: function-the-name-of-which-is-exactly-51-chars-long
              taskRef:
                apiVersion: custom.tekton.dev/v1alpha1
                kind: PipelineLoop
                name: pipeline-the-name-of-which-is-exactly-51-chars-long-b3de4-graph-function-the-name-of-which-is-exactly-51-chars-long
              params:
              - name: iter_num
                value: $(tasks.condition-cel.results.outcome)
              - name: just_one_iteration
                value:
                - '1'
              when:
              - input: $(tasks.condition-cel.results.outcome)
                operator: notin
                values:
                - '0'
          iterateParam: just_one_iteration
  timeout: 0s
```
inlined, although the recursive reference still point nowhere

long_name-false.yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-the-name-of-which-is-exactly-51-chars-long
  annotations:
    tekton.dev/output_artifacts: '{"print-iter": [{"key": "artifacts/$PIPELINERUN/print-iter/stdout.tgz",
      "name": "print-iter-stdout", "path": "/tmp/stdout"}]}'
    tekton.dev/input_artifacts: '{"print-iter": [{"name": "condition-cel-outcome",
      "parent_task": "condition-cel"}]}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print-iter": [["stdout", "$(results.stdout.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "42", "name": "iter_num",
      "optional": true, "type": "Integer"}], "name": "pipeline the name of which is
      exactly 51 chars long"}'
    tekton.dev/resource_templates: '[{"apiVersion": "custom.tekton.dev/v1alpha1",
      "kind": "PipelineLoop", "metadata": {"name": "pipeline-the-name-of-which-is-exactly-51-cha-174bd-graph-function-the-name-of-which-is-exactly-51-chars-long"},
      "spec": {"iterateParam": "just_one_iteration", "pipelineSpec": {"params": [{"name":
      "iter_num", "type": "string"}, {"name": "just_one_iteration", "type": "string"}],
      "tasks": [{"name": "condition-cel", "params": [{"name": "outcome", "value":
      "$(params.iter_num) - 1"}], "taskRef": {"apiVersion": "cel.tekton.dev/v1alpha1",
      "kind": "CEL", "name": "cel_condition"}}, {"name": "print-iter", "params": [{"name":
      "condition-cel-outcome", "value": "$(tasks.condition-cel.results.outcome)"}],
      "taskSpec": {"metadata": {"annotations": {"tekton.dev/template": ""}, "labels":
      {"pipelines.kubeflow.org/cache_enabled": "true", "pipelines.kubeflow.org/generation":
      "", "pipelines.kubeflow.org/pipelinename": ""}}, "params": [{"name": "condition-cel-outcome",
      "type": "string"}], "results": [{"description": "/tmp/stdout", "name": "stdout"}],
      "steps": [{"command": ["echo", "Iter: $(inputs.params.condition-cel-outcome)",
      ">", "$(results.stdout.path)"], "image": "alpine:3.6", "name": "main"}]}, "timeout":
      "0s"}, {"name": "function-the-name-of-which-is-exactly-51-chars-long", "params":
      [{"name": "just_one_iteration", "value": ["1"]}, {"name": "iter_num", "value":
      "$(tasks.condition-cel.results.outcome)"}], "taskRef": {"apiVersion": "custom.tekton.dev/v1alpha1",
      "kind": "PipelineLoop", "name": "pipeline-the-name-of-which-is-exactly-51-chars-long-174bd-graph-function-the-name-of-which-is-exactly-51-chars-long"},
      "when": [{"input": "$(tasks.condition-cel.results.outcome)", "operator": "notin",
      "values": ["0"]}]}]}}}]'
spec:
  params:
  - name: iter_num
    value: '42'
  pipelineSpec:
    params:
    - name: iter_num
      default: '42'
    tasks:
    - name: pipeline-the-name-of-which-is-exactly-51-cha-174bd-graph-function-the-name-of-which-is-exactly-51-chars-long
      taskRef:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        name: pipeline-the-name-of-which-is-exactly-51-cha-174bd-graph-function-the-name-of-which-is-exactly-51-chars-long
      params:
      - name: iter_num
        value: $(params.iter_num)
      - name: just_one_iteration
        value:
        - '1'
  timeout: 0s
```

Aside from not generating the resource, it has an additional flaw: the lacking resource's name is over the character limit (I think it's 64?) with enormous 108 of length, despite both the pipeline and the recursive function being below the limit, with 51 each (and 108 isn't even 51+51+1).

**Environment:**

* Python Version (use `python --version`): python 3.9.0
* SDK Version: master's HEAD, sha 008855a3f00e978936f4fe402f5309cd6cd98523
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
