### ISSUE TITLE
[SDK] No params passing for --taskSpec custom-tasks

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#687]
/kind bug

**What steps did you take and what happened:**
Reported to me by Kamil Huras from our team.

He passed params to a custom-task specified with --taskRef and --taskSpec option.

At least in some cases, for --taskRef the params have been generated:

```python
dsl.ContainerOp(
        name=custom_task_name,
        image=custom_task_image,
        command=[custom_task_command],
        arguments=[
            "--apiVersion", custom_task_api_version,
            "--kind", custom_task_kind,
            "--name", custom_task_resource_name,
            *custom_task_args,
            "--taskRef", custom_task_resource
        ],
        file_outputs={
            f"{result}": f"/{result}"
            for result in custom_task_results
        }
    )
```
results in:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: (...)
  annotations: (...)
spec:
  params:
  - name: foo-bar
    value: 'buzz'
  pipelineSpec:
    params:
    - name: foo-bar
      default: 'buzz'
    tasks:
    - name: upd
      params:
      - name: foo-bar
        value: '$(params.foo-bar)'
      taskRef:
        apiVersion: (...)
        kind: (...)
        name: (...)
  timeout: 0s
```

...but for --taskSpec they are not:

```python
dsl.ContainerOp(
        name=cel_name,
        image=CEL_TASK_IMAGE_NAME,
        command=["cel"],
        arguments=[
            "--apiVersion", CEL_API,
            "--kind", CEL_KIND,
            "--name", cel_resource_name,
            *cel_args,
            "--taskSpec", resource
        ],
        file_outputs={
            f"{result}": f"/{result}"
            for result in results
        }
    )
```
results in:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: (...)
  annotations: (...)
spec:
  params:
  - name: foo-bar
    value: 'buzz'
  pipelineSpec:
    params:
    - name: foo-bar
      default: 'buzz'
    tasks:
    - name: (...)
      taskSpec:
        apiVersion: (...)
        kind: (...)
        spec:
          params:
          - name: params-foo-bar
            alias: params.foo_bar
            type: string
          (...)
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            valid_container: "false"
            tekton.dev/template: ''
  timeout: 0s
```
Note how there are no `params` in the task, only in its `taskSpec.spec` (i.e. they are declared but not instantiated).

**What did you expect to happen:**
--taskRef and --taskSpec only differing in where the resource is generated (in separate file or annotation vs inline), not in whenever either one can be passed parameters.

**Additional information:**
Bug in the `_data_passing_rewriter.py`:
```python
if 'condition-' not in task['name'] and not task.get('taskRef', '')
```
while it should be:
```python
if 'condition-' not in task['name'] and not task.get('taskRef', '') and not task.get('taskSpec', ''):
```

**Environment:**

* Python Version (use `python --version`): 3.9.0
* SDK Version: sha 186a9e301f2fa5e2bd11e4f86f6cafb97c123db7
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
