### ISSUE TITLE
Data passing doesn't work if the pipeline parameter that get consumed as file.

### ISSUE THREAD

**Issue by huixa** [kubeflow/kfp-tekton#733]
/kind bug

**Issue**
1. Here is a simple KFP application:
```
import kfp
from kfp.components import create_component_from_func, InputPath
from kfp_tekton.compiler import TektonCompiler

# Consume as file
@create_component_from_func
def consume_anything_as_file(data_path: InputPath()):
    with open(data_path) as f:
        print("consume_anything_as_file: " + f.read())

# Pipeline
@kfp.dsl.pipeline(name='data_passing_pipeline')
def data_passing_pipeline(
    anything_param="anything_param",
):
    # Pass pipeline parameter; consume as file
    consume_anything_as_file(anything_param)

if __name__ == "__main__":
    kfp_endpoint = None
    TektonCompiler().compile(data_passing_pipeline, __file__.replace('.py', '.yaml'))
```
2. The generated yaml file is below:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: data-passing-pipeline
  annotations:
    tekton.dev/output_artifacts: '{}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"consume-anything-as-file": []}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "anything_param",
      "name": "anything_param", "optional": true}], "name": "data_passing_pipeline"}'
spec:
  params:
  - name: anything_param
    value: anything_param
  pipelineSpec:
    params:
    - name: anything_param
      default: anything_param
    tasks:
    - name: consume-anything-as-file
      taskSpec:
        steps:
        - name: main
          args:
          - --data
          - $(workspaces.consume-anything-as-file.path)/anything_param
          command:
          - sh
          - -ec
          - |
            program_path=$(mktemp)
            printf "%s" "$0" > "$program_path"
            python3 -u "$program_path" "$@"
          - |
            def consume_anything_as_file(data_path):
                with open(data_path) as f:
                    print("consume_anything_as_file: " + f.read())

            import argparse
            _parser = argparse.ArgumentParser(prog='Consume anything as file', description='')
            _parser.add_argument("--data", dest="data_path", type=str, required=True, default=argparse.SUPPRESS)
            _parsed_args = vars(_parser.parse_args())

            _outputs = consume_anything_as_file(**_parsed_args)
          image: python
          imagePullPolicy: IfNotPresent
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
              {"args": ["--data", {"inputPath": "data"}], "command": ["sh", "-ec",
              "program_path=$(mktemp)\nprintf \"%s\" \"$0\" > \"$program_path\"\npython3
              -u \"$program_path\" \"$@\"\n", "def consume_anything_as_file(data_path):\n    with
              open(data_path) as f:\n        print(\"consume_anything_as_file: \"
              + f.read())\n\nimport argparse\n_parser = argparse.ArgumentParser(prog=''Consume
              anything as file'', description='''')\n_parser.add_argument(\"--data\",
              dest=\"data_path\", type=str, required=True, default=argparse.SUPPRESS)\n_parsed_args
              = vars(_parser.parse_args())\n\n_outputs = consume_anything_as_file(**_parsed_args)\n"],
              "image": "python:3.7"}}, "inputs": [{"name": "data"}], "name": "Consume
              anything as file"}'
            tekton.dev/template: ''
        workspaces:
        - name: consume-anything-as-file
      timeout: 0s
      workspaces:
      - name: consume-anything-as-file
        workspace: data-passing-pipeline
    workspaces:
    - name: data-passing-pipeline
  timeout: 0s
  workspaces:
  - name: data-passing-pipeline
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 2Gi
        storageClassName: ""
```
3. The pvc and pv is ready:
```
[root@host xx]# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                     STORAGECLASS   REASON   AGE
pv-data-passing                            20Gi       RWX            Recycle          Bound    default/pvc-5af0e90116                            46m
pvc-68ca9226-240e-42d3-8612-5e7d264f5aa1   20Gi       RWO            Delete           Bound    kubeflow/minio-pvc        standard                22d
pvc-d50c8532-ceaa-4e29-bbf4-fb844b5ddc97   20Gi       RWO            Delete           Bound    kubeflow/mysql-pv-claim   standard                22d
[root@host xx]# kubectl get pvc
NAME             STATUS   VOLUME            CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-5af0e90116   Bound    pv-data-passing   20Gi       RWX                           43m
[root@host xx]# 
```
4. When run the yaml, but the result is:
```
[root@dstest11 liuhui]# kubectl get po
NAME                                                             READY   STATUS   RESTARTS   AGE
data-passing-pipeline-consume-anything-as-file-4q8lh-pod-jlcc5   0/1     Error    0          44m
[root@dstest11 liuhui]# kubectl logs data-passing-pipeline-consume-anything-as-file-4q8lh-pod-jlcc5
Traceback (most recent call last):
  File "/tmp/tmp.dHojU3JdGf", line 10, in <module>
    _outputs = consume_anything_as_file(**_parsed_args)
  File "/tmp/tmp.dHojU3JdGf", line 2, in consume_anything_as_file
    with open(data_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/consume-anything-as-file/anything_param'
[root@dstest11 liuhui]# 
```

**Expect Result:**
Should handle this case when use the pipeline parameter as file.

**Environment:**
* Python Version (use `python --version`):  Python 3.8.6
* SDK Version:  kfp-tekton SDK 1.0.0
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`): v1.21.1
* OS (e.g. from `/etc/os-release`): RHEL8.4
