### ISSUE TITLE
Multi-step (using size-estimations) tasks misdeclare outputs with underscore in the name

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#738]
/kind bug

**What steps did you take and what happened:**
Here is some script I used to checked whenever the paths in `tekton.dev/artifact_items` match the ones in the additional step generated due to using size-estimations:
```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import CEL_ConditionOp
import json, yaml


print_component = """
    name: print
    inputs:
    - name: stdin
    outputs:
    - name: {stdout}
    - name: {stderr}
    implementation:
      container:
        image: alpine:3.6
        command:
        - concat:
          - "echo "
          - {{ inputValue: stdin }}
          - " > "
          - {{ outputPath: {stdout} }}
          - " 2> "
          - {{ outputPath: {stderr} }}
  """

def print_op_singlestep(name: str, stdout_name: str = 'stdout', stderr_name: str = 'stderr'):
  c = print_component.format(stdout = stdout_name, stderr = stderr_name)
  obj = yaml.load(c, Loader=yaml.SafeLoader)
  obj['name'] = name
  c = yaml.dump(obj, indent=2)
  return load_component_from_text(c)

def print_op_multistep(name: str, stdout_name: str = 'stdout', stderr_name: str = 'stderr'):
  s = json.dumps({
    stdout_name: 2000,
    stderr_name: 2000,
  })

  c = print_component.format(stdout = stdout_name, stderr = stderr_name)
  obj = yaml.load(c, Loader = yaml.SafeLoader)
  obj['name'] = name
  obj.setdefault('metadata', {}).setdefault('annotations', {})['tekton-result-sizes'] = s
  c = yaml.dump(obj, indent=2)
  return load_component_from_text(c)


@dsl.pipeline("artifact_items_test")
def artifact_items_test():
  print_op_singlestep("print00", "stdout")("all singlestep_work_fine")
  print_op_singlestep("print01", "std-out")("all singlestep_work_fine")
  print_op_singlestep("print02", "std_out")("all singlestep_work_fine")

  print_op_multistep("print10", "stdout")("no underscore - works")
  print_op_multistep("print11", "std-out")("no underscore - works")
  print_op_multistep("print12", "std_out")("has underscore - does not work")

def compile_pipeline(fname: str) -> None:
  from kfp_tekton.compiler import TektonCompiler as Compiler
  Compiler().compile(artifact_items_test, fname)

def test_pipeline(pip: dict) -> None:
  artifact_items = json.loads(pip['metadata']['annotations']['tekton.dev/artifact_items'])
  tasks = {
    task['name']: task for task in pip['spec']['pipelineSpec']['tasks']
  }
  for task_name, artifacts in artifact_items.items():
    print(f"task: {task_name}")
    task = tasks[task_name]
    non_main_items = {
      artifact[0]: artifact[1]
      for artifact in artifacts
      # $(results.sth.path) aren't interesting
      if not artifact[1].startswith('$')
    }

    first_item = list(non_main_items.keys())[0] if len(non_main_items) > 0 else None
    other_items = {
      artifact[0]: artifact[1]
      for artifact in artifacts
      if artifact[0] not in non_main_items
    }

    for item_name, _ in other_items.items():
      print(f"- {item_name:7} - main")

    if task_name.startswith('print0'):
      msg = f"single-step items should all put artifact in main step, untrue for tasks.{task_name}.results.{first_item}"
      assert len(non_main_items) == 0, msg
      continue
    else: 
      msg = f"multi-step items with big sizes should put some artifacts in next step, untrue for tasks.{task_name}"
      assert len(non_main_items) == 1, msg

    declared_path = non_main_items[first_item]
    next_step = task['taskSpec']['steps'][1] # after "main"
    lines = next_step['args'][0].splitlines()
    last_mv = lines[-1].strip(';').strip(' ')
    assert last_mv.startswith('mv ')
    actual_path = last_mv.split()[-1]
    if declared_path == actual_path:
      print(f"- {first_item:7} - copy")
    else:
      print(f"- {first_item:7} - copy, DIFF")
      print(f"    declared: \"{declared_path}\"")
      print(f"    actual:   \"{actual_path}\"")

if __name__ == '__main__':
  fname = __file__.replace('.py', '.yaml')
  compile_pipeline(fname)
  with open(fname) as f:
    pip = yaml.load(f, Loader=yaml.SafeLoader)
  test_pipeline(pip)
```

Output:
```
task: print00
- stderr  - main
- stdout  - main
task: print01
- std-out - main
- stderr  - main
task: print02
- std_out - main
- stderr  - main
task: print10
- stderr  - main
- stdout  - copy
task: print11
- stderr  - main
- std-out - copy
task: print12
- stderr  - main
- std_out - copy, DIFF
    declared: "/tekton/home/tep-results/std_out"
    actual:   "/tekton/home/tep-results/std-out"
```

Looking at the yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: artifact-items-test
  annotations:
    (...)
    tekton.dev/artifact_items: '{(...), "print12": [["std_out", "/tekton/home/tep-results/std_out"],
      ["stderr", "$(results.stderr.path)"]]}'
    (...)
spec:
  pipelineSpec:
    tasks:
    (...)
    - name: print12
      taskSpec:
        steps:
        - name: main
          command:
          - echo has underscore - does not work > $(results.std-out.path) 2> /tekton/home/tep-results/stderr
          image: alpine:3.6
        - name: copy-results-1
          args:
          - |
            mv /tekton/home/tep-results/stderr $(results.stderr.path);
            mv $(results.std-out.path) /tekton/home/tep-results/std-out;
          command:
          - sh
          - -c
          image: library/bash
        (...)
      timeout: 0s
  timeout: 0s
```

Indeed, the path in the annotation and in the actual tekton task step do differ.

**What did you expect to happen:**

```
task: print00
- stderr  - main
- stdout  - main
task: print01
- std-out - main
- stderr  - main
task: print02
- std_out - main
- stderr  - main
task: print10
- stderr  - main
- stdout  - copy
task: print11
- stderr  - main
- std-out - copy
task: print12
- stderr  - main
- std_out - copy
```

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: artifact-items-test
  annotations:
    (...)
    tekton.dev/artifact_items: '{(...), "print12": [["std_out", "/tekton/home/tep-results/std-out"],
      ["stderr", "$(results.stderr.path)"]]}'
    (...)
spec:
  pipelineSpec:
    tasks:
    (...)
    - name: print12
      taskSpec:
        steps:
        - name: main
          command:
          - echo has underscore - does not work > $(results.std-out.path) 2> /tekton/home/tep-results/stderr
          image: alpine:3.6
        - name: copy-results-1
          args:
          - |
            mv /tekton/home/tep-results/stderr $(results.stderr.path);
            mv $(results.std-out.path) /tekton/home/tep-results/std-out;
          command:
          - sh
          - -c
          image: library/bash
        (...)
      timeout: 0s
  timeout: 0s
```

**Additional information:**
Those paths are created at the very end of `_op_to_template.py`:
```python
for i, artifact in enumerate(artifact_items[op.name]):
    if artifact[0] not in verified_result_size_map[step_counter].keys():
        artifact[1] = '%s%s' % (TEKTON_HOME_RESULT_PATH, artifact[0])
        artifact_items[op.name][i] = artifact
```
Notably, `artifact[0]` is not sanitised. After adding sanitisation:
```python
for i, artifact in enumerate(artifact_items[op.name]):
    if artifact[0] not in verified_result_size_map[step_counter].keys():
        artifact[1] = '%s%s' % (TEKTON_HOME_RESULT_PATH, sanitize_k8s_name(artifact[0]))
        artifact_items[op.name][i] = artifact
```
the result is:
```
task: print00
- stderr  - main
- stdout  - main
task: print01
- std-out - main
- stderr  - main
task: print02
- std_out - main
- stderr  - main
task: print10
- stderr  - main
- stdout  - copy
task: print11
- stderr  - main
- std-out - copy
task: print12
- stderr  - main
- std_out - copy
```
i.e. as expected.

**Environment:**

* Python Version (use `python --version`): 3.9.0
* SDK Version: 043d7341473f70ddf6b195c21e24756fd06df65a
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
