### ISSUE TITLE
Loops: some loops create wrong "when" links

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#761]
/kind bug

**What steps did you take and what happened:**
cond_loop.py:
```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import CEL_ConditionOp,


PrintOp = load_component_from_text("""
  name: print
  inputs:
  - name: msg
  outputs:
  - name: stdout
  implementation:
    container:
      image: alpine:3.6
      command:
      - concat:
        - "echo "
        - { inputValue: msg }
""")


@dsl.pipeline("cond-loop-0")
def cond_loop_0(param: list = ["a", "b", "c"]):
  start_cond = CEL_ConditionOp(f"size({param}) > 0").output
  with dsl.Condition(start_cond == "true"):
    with dsl.ParallelFor(param):
      PrintOp("Fails to at Tekton validation!")

@dsl.pipeline("cond-loop-1")
def cond_loop_1(param: list = ["a", "b", "c"]):
  start_cond = CEL_ConditionOp(f"size({param}) > 0").output
  with dsl.Condition(start_cond == "true"):
    with dsl.ParallelFor(param):
      pass


if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  from kfp_tekton.compiler.pipeline_utils import TektonPipelineConf
  tekton_pipeline_conf = TektonPipelineConf()
  tekton_pipeline_conf.set_tekton_inline_spec(True)
  tekton_pipeline_conf.set_resource_in_separate_yaml(True)
  Compiler().compile(cond_loop_0, __file__.replace('.py', '-0.yaml'), tekton_pipeline_conf=tekton_pipeline_conf)
  Compiler().compile(cond_loop_1, __file__.replace('.py', '-1.yaml'), tekton_pipeline_conf=tekton_pipeline_conf)
```

Generated cond_loop-0.yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cond-loop-0
  annotations:
    tekton.dev/output_artifacts: '{"print": [{"key": "artifacts/$PIPELINERUN/print/stdout.tgz",
      "name": "print-stdout", "path": "/tmp/outputs/stdout/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print": [["stdout", "$(results.stdout.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "[\"a\", \"b\",
      \"c\"]", "name": "param", "optional": true, "type": "JsonArray"}], "name": "cond-loop-0"}'
spec:
  params:
  - name: param
    value: '["a", "b", "c"]'
  pipelineSpec:
    params:
    - name: param
      default: '["a", "b", "c"]'
    tasks:
    - name: condition-cel
      params:
      - name: outcome
        value: size($(inputs.params.param)) > 0
      taskRef:
        name: cel_condition
        apiVersion: cel.tekton.dev/v1alpha1
        kind: CEL
    - name: cond-loop-0-47426-for-loop-2
      params:
      - name: condition-cel-outcome
        value: $(tasks.condition-cel.results.outcome)
      - name: param-loop-item
        value: $(params.param)
      when:
      - input: $(tasks.condition-cel.results.outcome)
        operator: in
        values:
        - "true"
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: condition-cel-outcome
              type: string
            - name: param-loop-item
              type: string
            tasks:
            - name: print
              taskSpec:
                steps:
                - name: main
                  command:
                  - echo Fails to at Tekton validation!
                  image: alpine:3.6
                - image: busybox
                  name: copy-results
                  script: |
                    #!/bin/sh
                    set -exo pipefail
                    cp /tmp/outputs/stdout/data $(results.stdout.path);
                results:
                - name: stdout
                  description: /tmp/outputs/stdout/data
                stepTemplate:
                  volumeMounts:
                  - name: stdout
                    mountPath: /tmp/outputs/stdout
                volumes:
                - name: stdout
                  emptyDir: {}
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
                  annotations:
                    pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
                      {"command": [{"concat": ["echo ", {"inputValue": "msg"}]}],
                      "image": "alpine:3.6"}}, "inputs": [{"name": "msg"}], "name":
                      "print", "outputs": [{"name": "stdout"}]}'
                    tekton.dev/template: ''
              timeout: 0s
          iterateParam: param-loop-item
  timeout: 0s
```

Generated cond_loop-1.yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cond-loop-1
  annotations:
    tekton.dev/output_artifacts: '{}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "[\"a\", \"b\",
      \"c\"]", "name": "param", "optional": true, "type": "JsonArray"}], "name": "cond-loop-1"}'
spec:
  params:
  - name: param
    value: '["a", "b", "c"]'
  pipelineSpec:
    params:
    - name: param
      default: '["a", "b", "c"]'
    tasks:
    - name: condition-cel
      params:
      - name: outcome
        value: size($(inputs.params.param)) > 0
      taskRef:
        name: cel_condition
        apiVersion: cel.tekton.dev/v1alpha1
        kind: CEL
    - name: cond-loop-1-eec98-for-loop-2
      params:
      - name: param-loop-item
        value: $(params.param)
      when:
      - input: $(tasks.condition-cel-outcome.results.outcome)
        operator: in
        values:
        - "true"
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: param-loop-item
              type: string
            tasks: []
          iterateParam: param-loop-item
  timeout: 0s
```

Note how the first variant's `when` contains:
```
input: $(tasks.condition-cel.results.outcome)
```
but the second one is:
```
input: $(tasks.condition-cel-outcome.results.outcome)
```

There is no such a task as `condition-cel-outcome`. It looks like concatenated task-name + param-name.

I'm not sure in which other cases it happens, but it does happen for empty loops for sure.

**What did you expect to happen:**

Both variants working fine:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cond-loop-1
  annotations:
    tekton.dev/output_artifacts: '{}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "[\"a\", \"b\",
      \"c\"]", "name": "param", "optional": true, "type": "JsonArray"}], "name": "cond-loop-1"}'
spec:
  params:
  - name: param
    value: '["a", "b", "c"]'
  pipelineSpec:
    params:
    - name: param
      default: '["a", "b", "c"]'
    tasks:
    - name: condition-cel
      params:
      - name: outcome
        value: size($(inputs.params.param)) > 0
      taskRef:
        name: cel_condition
        apiVersion: cel.tekton.dev/v1alpha1
        kind: CEL
    - name: cond-loop-1-eec98-for-loop-2
      params:
      - name: param-loop-item
        value: $(params.param)
      when:
      - input: $(tasks.condition-cel.results.outcome)
        operator: in
        values:
        - "true"
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: param-loop-item
              type: string
            tasks: []
          iterateParam: param-loop-item
  timeout: 0s
```

**Additional information:**
It looks like this code origins from compiler.py:
```python
map_cel_vars = lambda a: '$(tasks.%s.results.%s)' % (sanitize_k8s_name(a['value'].split('.')[-1]),
  sanitize_k8s_name(a['output_name'])) if a.get('type', '') == dsl.PipelineParam else a.get('value', '')

condition_refs[template['metadata']['name']] = [
  {
    'input': map_cel_vars(condition_operand1),
    'operator': conditionOp_mapping[condition_operator['value']],
    'values': [map_cel_vars(condition_operand2)]
  }
]
```

but `condition_operand1` is, respectively:
*  for cond-loop-0: `{'name': 'operand1', 'value': '$(params.condition-cel)', 'type': <class 'kfp.dsl._pipeline_param.PipelineParam'>, 'op_name': 'condition-cel', 'output_name': 'outcome'}`
* for cond-loop-1: `{'name': 'operand1', 'value': '$(params.condition-cel-outcome)', 'type': <class 'kfp.dsl._pipeline_param.PipelineParam'>, 'op_name': 'condition-cel', 'output_name': 'outcome'}`

So it takes `'value'` and splits it until the dot, getting `"condition-cel)"` and `"condition-cel-outcome)"` respectively, and then sanitises it, to get `"condition-cel"` and `"condition-cel-outcome"`.

It seems to me that this bug can be completely avoided simply by using `'op_name'` instead.

**Environment:**

* Python Version (use `python --version`): python 3.9.0
* SDK Version: 1eea71606b6aa90664beba4ef732b234ac4070d0
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
