### ISSUE TITLE
"Break" in first iteration sets invalid status

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#819]
/kind bug

**What steps did you take and what happened:**
```python
from kfp import dsl, components
from kfp.components import load_component_from_text
from kfp_tekton import tekton
from kfp_tekton.tekton import CEL_ConditionOp


def pipeline_for_lit(lit: int):
  @dsl.pipeline(name='pipeline')
  def pipeline():
      loop_args = [1, 2]
      with dsl.ParallelFor(loop_args, parallelism=1) as item:
          condi_1 = tekton.CEL_ConditionOp(f"{item} == {lit}").output
          with dsl.Condition(condi_1 == 'true'):
              tekton.Break()
  return pipeline

if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  from kfp_tekton.compiler.pipeline_utils import TektonPipelineConf
  tekton_pipeline_conf = TektonPipelineConf()
  tekton_pipeline_conf.set_tekton_inline_spec(True)
  Compiler().compile(pipeline_for_lit(1), __file__.replace('.py', '-1.yaml'), tekton_pipeline_conf=tekton_pipeline_conf)
  Compiler().compile(pipeline_for_lit(2), __file__.replace('.py', '-2.yaml'), tekton_pipeline_conf=tekton_pipeline_conf)
```

Then run both variants on cluster a few times.

Sometimes it works fine but sometimes, either variant produces a run yaml similar to the following:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata: (...)
spec:
  params: []
  pipelineSpec:
    params: []
    tasks:
    - name: pipeline-b1810-for-loop-2
      params:
      - name: loop-item-param-1
        value: '[1, 2]'
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        metadata: {}
        params:
        - name: loop-item-param-1
          type: string
        spec:
          iterateParam: loop-item-param-1
          parallelism: 1
          pipelineSpec:
            params:
            - name: loop-item-param-1
              type: string
            tasks:
            - name: condition-cel
              (...)
            - name: pipelineloop-break-operation
              (...)
              when:
              - input: $(tasks.condition-cel.results.outcome)
                operator: in
                values:
                - "true"
  podTemplate: {}
  timeout: 8760h0m0s
status:
  completionTime: "2022-01-11T12:50:58Z"
  conditions:
  - lastTransitionTime: "2022-01-11T12:50:58Z"
    message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  pipelineSpec:
    params:
    - default: "10"
      name: param
      type: string
    tasks: (...)
  runs:
    pipeline-pipeline-b1810-for-loop-2:
      pipelineTaskName: pipeline-b1810-for-loop-2
      status:
        completionTime: "2022-01-11T12:50:58Z"
        conditions:
        - lastTransitionTime: "2022-01-11T12:50:58Z"
          message: PipelineRuns completed successfully with the conditions are met
          reason: Succeeded
          status: "True"
          type: Succeeded
        extraFields:
          currentRunning: 1
          pipelineLoopSpec:
            iterateNumeric: ""
            iterateParam: loop-item-param-1
            parallelism: 1
            pipelineSpec: (...)
          pipelineRuns:
            pipeline-pipeline-b1810-for-loop-2-00001-gtxnt:
              iteration: 1
              status:
                conditions:
                - lastTransitionTime: "2022-01-11T12:50:57Z"
                  message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Incomplete:
                    1, Skipped: 0'
                  reason: Running
                  status: Unknown
                  type: Succeeded
                pipelineSpec: (...)
                runs:
                  pipeline-pipeline-b1810-for-loop-2-00001-gtxnt-condition-cel:
                    pipelineTaskName: condition-cel
                    status:
                      (...)
                      results:
                      - name: outcome
                        value: "true"
                startTime: "2022-01-11T12:50:56Z"
                taskRuns:
                  pic6fb2078957077e6da87fe489604725e-pipelineloop-break-operation:
                    pipelineTaskName: pipelineloop-break-operation
                    status:
                      podName: ""
        observedGeneration: 1
        results:
        - name: condition
          value: pass
        startTime: "2022-01-11T12:50:56Z"
  startTime: "2022-01-11T12:50:56Z"
```
(for `-2` variant the first iteration is correct and the second one looks like the above)

**What did you expect to happen:**
Compare what the Run claims about its PipelineRuns:
```yaml
message: PipelineRuns completed successfully with the conditions are met
reason: Succeeded
status: "True"
type: Succeeded
```
vs what the actual status of the last PipelineRun is (at least sometimes):
```yaml
message: 'Tasks Completed: 1 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0'
reason: Running
status: Unknown
type: Succeeded
```
i.e. the Run claims that all PipelineRuns were completed, but the last PipelineRun seems to claim it's still running.

What was expected is all PipelineRuns (in this case --- one) to actually be Succeeded when the Run is set to Succeeded:
```yaml
message: 'Tasks Completed: 2 (Failed: 0, Cancelled 0), Skipped: 0'
reason: Succeeded
status: "True"
type: Succeeded
```
It's easy to see in `-2`, as it contains both a Succeeded and Running iterations.

**Additional information:**
We initially thought it was related to `lit == 1`, but it turned out it seems to happen randomly for `lit == 2` too, so it might be that it happens independently of the number of iterations.

It could be that the PipelineRun would simply continue execution were there more tasks in it, we haven't tested that yet.

**Environment:**

* Python Version (use `python --version`): irrelevant
* SDK Version: b16bd8863aaf36de240b7306f501d62b95f01f31
* Tekton Version (use `tkn version`): v0.30.0
* Kubernetes Version (use `kubectl version`):
  * Client Version: v1.22.1
  * Server Version: v1.20.13+IKS
* OS (e.g. from `/etc/os-release`): irrelevant
