### ISSUE TITLE
bug(controllers) PipelineLoop doesn't support podTemplate and taskRunSpecs

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#879]
/kind bug

**What steps did you take and what happened:**
Add a valid `podTemplate` and `taskRunSpecs` entry to any loop example. Typical use-case would be to add:
```yaml
apiVersion: custom.tekton.dev/v1alpha1
kind: PipelineLoop
metadata:
  name: pipeline-abc
spec:
  pipelineSpec:
    (...)
    tasks:
    - name: task-a
      (...)
    - name: task-b
      (...)
    - name: task-c
      (...)
    - name: task-that-needs-account-token
      (...)
  podTemplate:
    automountServiceAccountToken: false
  taskRunSpecs:
  - pipelineTaskName: task-that-needs-account-token
    taskPodTemplate:
      podTemplate:
        automountServiceAccountToken: true
---
apiVersion: custom.tekton.dev/v1alpha1
kind: PipelineRun
metadata: (...)
spec:
  pipelineSpec:
    (...)
    tasks:
    - name: task-abc
      taskRef:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        name: pipeline-abc
    - name: task-def
      (...)
  podTemplate:
    automountServiceAccountToken: false
```

It fails on Tekton validation of that field, calling those fields unknown.

**What did you expect to happen:**
PipelineLoop to accepting any fields that PipelineRun would.

**Additional information:**
In PipelineLoop pkg I can see:
```go
// PipelineLoopSpec defines the desired state of the PipelineLoop
type PipelineLoopSpec struct {
	// TaskRef is a reference to a task definition.
	// +optional
	// TaskRef     *v1beta1.TaskRef     `json:"taskRef,omitempty"`
	PipelineRef *v1beta1.PipelineRef `json:"pipelineRef,omitempty"`

	// TaskSpec is a specification of a task
	// +optional
	PipelineSpec *v1beta1.PipelineSpec `json:"pipelineSpec,omitempty"`

	// IterateParam is the name of the task parameter that is iterated upon.
	IterateParam string `json:"iterateParam"`

	// The separator for IterateParam if the IterateParam is a strings with separator char, this field is optional.
	// +optional
	IterateParamSeparator string `json:"iterateParamStringSeparator,omitempty"`

	IterateNumeric string `json:"iterateNumeric"`

	// Time after which the TaskRun times out.
	// +optional
	Timeout *metav1.Duration `json:"timeout,omitempty"`

	// Parallelism represents how many pipelines can be triggered simutaniously by the loop.
	// +optional
	Parallelism int `json:"parallelism,omitempty"`

	// Retries represents how many times a task should be retried in case of task failure.
	// +optional
	Retries int `json:"retries,omitempty"`

	// Workspace to a volume mapping to be consumed by a PipelineRun.
	// +optional
	Workspaces []v1beta1.WorkspaceBinding `json:"workspaces,omitempty"`
}
```
i.e. contains `Workspaces` but not `PodTempalte` or `TaskRunSpecs`, as in `PipelineRunSpec`:
```go
// PipelineRunSpec defines the desired state of PipelineRun
type PipelineRunSpec struct {
	// +optional
	PipelineRef *PipelineRef `json:"pipelineRef,omitempty"`
	// +optional
	PipelineSpec *PipelineSpec `json:"pipelineSpec,omitempty"`
	// Resources is a list of bindings specifying which actual instances of
	// PipelineResources to use for the resources the Pipeline has declared
	// it needs.
	Resources []PipelineResourceBinding `json:"resources,omitempty"`
	// Params is a list of parameter names and values.
	Params []Param `json:"params,omitempty"`
	// +optional
	ServiceAccountName string `json:"serviceAccountName,omitempty"`

	// Deprecated: use taskRunSpecs.ServiceAccountName instead
	// +optional
	ServiceAccountNames []PipelineRunSpecServiceAccountName `json:"serviceAccountNames,omitempty"`
	// Used for cancelling a pipelinerun (and maybe more later on)
	// +optional
	Status PipelineRunSpecStatus `json:"status,omitempty"`
	// This is an alpha field. You must set the "enable-api-fields" feature flag to "alpha"
	// for this field to be supported.
	//
	// Time after which the Pipeline times out.
	// Currently three keys are accepted in the map
	// pipeline, tasks and finally
	// with Timeouts.pipeline >= Timeouts.tasks + Timeouts.finally
	// +optional
	Timeouts *TimeoutFields `json:"timeouts,omitempty"`
	// Time after which the Pipeline times out. Defaults to never.
	// Refer to Go's ParseDuration documentation for expected format: https://golang.org/pkg/time/#ParseDuration
	// +optional
	Timeout *metav1.Duration `json:"timeout,omitempty"`
	// PodTemplate holds pod specific configuration
	PodTemplate *PodTemplate `json:"podTemplate,omitempty"`
	// Workspaces holds a set of workspace bindings that must match names
	// with those declared in the pipeline.
	// +optional
	Workspaces []WorkspaceBinding `json:"workspaces,omitempty"`
	// TaskRunSpecs holds a set of runtime specs
	// +optional
	TaskRunSpecs []PipelineTaskRunSpec `json:"taskRunSpecs,omitempty"`
}
```

I can see that the source code does mention some of those as "TODO":
```go
func (c *Reconciler) createPipelineRun(ctx context.Context, logger *zap.SugaredLogger, tls *pipelineloopv1alpha1.PipelineLoopSpec, run *v1alpha1.Run, iteration int, iterationElements []interface{}) (*v1beta1.PipelineRun, error) {

	// Create name for PipelineRun from Run name plus iteration number.
	prName := names.SimpleNameGenerator.RestrictLengthWithRandomSuffix(fmt.Sprintf("%s-%s", run.Name, fmt.Sprintf("%05d", iteration)))
	pipelineRunAnnotations := getPipelineRunAnnotations(run)
	currentIndex := iteration - 1
	if currentIndex > len(iterationElements) {
		currentIndex = len(iterationElements) - 1
	}
	currentIterationItemBytes, _ := json.Marshal(iterationElements[currentIndex])
	pipelineRunAnnotations[pipelineloop.GroupName+pipelineLoopCurrentIterationItemAnnotationKey] = string(currentIterationItemBytes)

	pr := &v1beta1.PipelineRun{
		ObjectMeta: metav1.ObjectMeta{
			Name:      prName,
			Namespace: run.Namespace,
			OwnerReferences: []metav1.OwnerReference{*metav1.NewControllerRef(run,
				schema.GroupVersionKind{Group: "tekton.dev", Version: "v1alpha1", Kind: "Run"})},
			Labels:      getPipelineRunLabels(run, strconv.Itoa(iteration)),
			Annotations: pipelineRunAnnotations,
		},
		Spec: v1beta1.PipelineRunSpec{
			Params:             getParameters(run, tls, iteration),
			Timeout:            tls.Timeout,
			ServiceAccountName: "",  // TODO: Implement service account name
			PodTemplate:        nil, // TODO: Implement pod template
			Workspaces:         tls.Workspaces,
		}}

	if tls.PipelineRef != nil {
		pr.Spec.PipelineRef = &v1beta1.PipelineRef{
			Name: tls.PipelineRef.Name,
			// Kind: tls.PipelineRef.Kind,
		}
	} else if tls.PipelineSpec != nil {
		pr.Spec.PipelineSpec = tls.PipelineSpec
	}

	logger.Infof("Creating a new PipelineRun object %s", prName)
	return c.pipelineClientSet.TektonV1beta1().PipelineRuns(run.Namespace).Create(ctx, pr, metav1.CreateOptions{})

}
```

**Environment:**

* Python Version (use `python --version`): irrelevant
* SDK Version: irrelevant
* Tekton Version (use `tkn version`): v0.30.0
* Kubernetes Version (use `kubectl version`): v1.21.10+IKS
* OS (e.g. from `/etc/os-release`): irrelevant
