### ISSUE TITLE
(sdk) Outer loop doesn't pass inner loop's item's source

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#913]
/kind bug

**What steps did you take and what happened:**
Create two a nested loop, which both levels iterating over the same parameter. Inner-most, create a single task that does NOT use that parameter.
```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import CEL_ConditionOp
from kfp_tekton.compiler import TektonCompiler


class Coder:
  def empty(self):
    return ""


TektonCompiler._get_unique_id_code = Coder.empty


def PrintOp(name: str, msg: str = None):
  if msg is None:
    msg = name
  print_op = load_component_from_text(
  """
  name: %s
  inputs:
  - {name: input_text, type: String, description: 'Represents an input parameter.'}
  outputs:
  - {name: output_value, type: String, description: 'Represents an output paramter.'}
  implementation:
    container:
      image: alpine:3.6
      command:
      - sh
      - -c
      - |
        set -e
        echo $0 > $1
      - {inputValue: input_text}
      - {outputPath: output_value}
  """ % (name)
  )
  return print_op(msg)


@dsl.pipeline("empty-loop")
def nested_loop(param: list = ["a", "b", "c"]):
  # param of the inner loop is used inner-most --- works fine
  with dsl.ParallelFor(param):
    with dsl.ParallelFor(param):
      PrintOp('print-0', f"print {param}")

  # param of the inner loop is not used inner-most --- fails
  with dsl.ParallelFor(param):
    with dsl.ParallelFor(param):
      PrintOp('print-1', "print")


if __name__ == '__main__':
  TektonCompiler().compile(nested_loop, __file__.replace('.py', '.yaml'))
```
which generates the following yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: empty-loop
  annotations:
    tekton.dev/output_artifacts: '{"print-0": [{"key": "artifacts/$PIPELINERUN/print-0/output_value.tgz",
      "name": "print-0-output_value", "path": "/tmp/outputs/output_value/data"}],
      "print-1": [{"key": "artifacts/$PIPELINERUN/print-1/output_value.tgz", "name":
      "print-1-output_value", "path": "/tmp/outputs/output_value/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print-0": [["output_value", "$(results.output-value.path)"]],
      "print-1": [["output_value", "$(results.output-value.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "[\"a\", \"b\",
      \"c\"]", "name": "param", "optional": true, "type": "JsonArray"}], "name": "empty-loop"}'
spec:
  params:
  - name: param
    value: '["a", "b", "c"]'
  pipelineSpec:
    params:
    - name: param
      default: '["a", "b", "c"]'
    tasks:
    - name: empty-loop-for-loop-1
      params:
      - name: param
        value: $(params.param)
      - name: param-loop-item
        value: $(params.param)
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: param
              type: string
            - name: param-loop-item
              type: string
            tasks:
            - name: empty-loop-for-loop-2
              params:
              - name: param
                value: $(params.param)
              - name: param-loop-item
                value: $(params.param)
              taskSpec:
                apiVersion: custom.tekton.dev/v1alpha1
                kind: PipelineLoop
                spec:
                  pipelineSpec:
                    params:
                    - name: param
                      type: string
                    - name: param-loop-item
                      type: string
                    tasks:
                    - name: print-0
                      params:
                      - name: param
                        value: $(params.param)
                      taskSpec:
                        steps:
                        - name: main
                          command:
                          - sh
                          - -c
                          - |
                            set -e
                            echo $0 > $1
                          - print $(inputs.params.param)
                          - $(results.output-value.path)
                          image: alpine:3.6
                        params:
                        - name: param
                          type: string
                        results:
                        - name: output-value
                          description: /tmp/outputs/output_value/data
                        metadata:
                          labels:
                            pipelines.kubeflow.org/pipelinename: ''
                            pipelines.kubeflow.org/generation: ''
                            pipelines.kubeflow.org/cache_enabled: "true"
                          annotations:
                            pipelines.kubeflow.org/component_spec_digest: '{"name":
                              "print-0", "outputs": [{"description": "Represents an
                              output paramter.", "name": "output_value", "type": "String"}],
                              "version": "print-0@sha256=5dd3c506ec54281b82008ca8ec5d8142834eae18d74ce8a110a31dd6e371b40d"}'
                            tekton.dev/template: ''
                      timeout: 525600m
                  iterateParam: param-loop-item
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
          iterateParam: param-loop-item
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
    - name: empty-loop-for-loop-3
      params:
      - name: param-loop-item
        value: $(params.param)
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: param-loop-item
              type: string
            tasks:
            - name: empty-loop-for-loop-4
              params:
              - name: param-loop-item
                value: $(params.param)
              taskSpec:
                apiVersion: custom.tekton.dev/v1alpha1
                kind: PipelineLoop
                spec:
                  pipelineSpec:
                    params:
                    - name: param-loop-item
                      type: string
                    tasks:
                    - name: print-1
                      taskSpec:
                        steps:
                        - name: main
                          command:
                          - sh
                          - -c
                          - |
                            set -e
                            echo $0 > $1
                          - print
                          - $(results.output-value.path)
                          image: alpine:3.6
                        results:
                        - name: output-value
                          description: /tmp/outputs/output_value/data
                        metadata:
                          labels:
                            pipelines.kubeflow.org/pipelinename: ''
                            pipelines.kubeflow.org/generation: ''
                            pipelines.kubeflow.org/cache_enabled: "true"
                          annotations:
                            pipelines.kubeflow.org/component_spec_digest: '{"name":
                              "print-1", "outputs": [{"description": "Represents an
                              output paramter.", "name": "output_value", "type": "String"}],
                              "version": "print-1@sha256=3b81342bc143f625b58ebdb01e7c83b145880dee807be35c1e16fdb835d46580"}'
                            tekton.dev/template: ''
                      timeout: 525600m
                  iterateParam: param-loop-item
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
          iterateParam: param-loop-item
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
  timeout: 525600m
```
Note that for the first case, loop 1 & 2, the parameter `param` is passed, as its used in the inner loop's body.

For loops 3 & 4, the parameter isn't passed.

I noticed that in some cases the parameter is also passed to the PipelineLoop customt ask, but not to its `pipelineSpec`'s params.

**What did you expect to happen:**
Parameter being passed just fine:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: empty-loop
  annotations:
    tekton.dev/output_artifacts: '{"print-0": [{"key": "artifacts/$PIPELINERUN/print-0/output_value.tgz",
      "name": "print-0-output_value", "path": "/tmp/outputs/output_value/data"}],
      "print-1": [{"key": "artifacts/$PIPELINERUN/print-1/output_value.tgz", "name":
      "print-1-output_value", "path": "/tmp/outputs/output_value/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print-0": [["output_value", "$(results.output-value.path)"]],
      "print-1": [["output_value", "$(results.output-value.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": "[\"a\", \"b\",
      \"c\"]", "name": "param", "optional": true, "type": "JsonArray"}], "name": "empty-loop"}'
spec:
  params:
  - name: param
    value: '["a", "b", "c"]'
  pipelineSpec:
    params:
    - name: param
      default: '["a", "b", "c"]'
    tasks:
    - name: empty-loop-for-loop-1
      params:
      - name: param
        value: $(params.param)
      - name: param-loop-item
        value: $(params.param)
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: param
              type: string
            - name: param-loop-item
              type: string
            tasks:
            - name: empty-loop-for-loop-2
              params:
              - name: param
                value: $(params.param)
              - name: param-loop-item
                value: $(params.param)
              taskSpec:
                apiVersion: custom.tekton.dev/v1alpha1
                kind: PipelineLoop
                spec:
                  pipelineSpec:
                    params:
                    - name: param
                      type: string
                    - name: param-loop-item
                      type: string
                    tasks:
                    - name: print-0
                      params:
                      - name: param
                        value: $(params.param)
                      taskSpec:
                        steps:
                        - name: main
                          command:
                          - sh
                          - -c
                          - |
                            set -e
                            echo $0 > $1
                          - print $(inputs.params.param)
                          - $(results.output-value.path)
                          image: alpine:3.6
                        params:
                        - name: param
                          type: string
                        results:
                        - name: output-value
                          description: /tmp/outputs/output_value/data
                        metadata:
                          labels:
                            pipelines.kubeflow.org/pipelinename: ''
                            pipelines.kubeflow.org/generation: ''
                            pipelines.kubeflow.org/cache_enabled: "true"
                          annotations:
                            pipelines.kubeflow.org/component_spec_digest: '{"name":
                              "print-0", "outputs": [{"description": "Represents an
                              output paramter.", "name": "output_value", "type": "String"}],
                              "version": "print-0@sha256=5dd3c506ec54281b82008ca8ec5d8142834eae18d74ce8a110a31dd6e371b40d"}'
                            tekton.dev/template: ''
                      timeout: 525600m
                  iterateParam: param-loop-item
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
          iterateParam: param-loop-item
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
    - name: empty-loop-for-loop-3
      params:
      - name: param
        value: $(params.param)
      - name: param-loop-item
        value: $(params.param)
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: param
              type: string
            - name: param-loop-item
              type: string
            tasks:
            - name: empty-loop-for-loop-4
              params:
              - name: param-loop-item
                value: $(params.param)
              taskSpec:
                apiVersion: custom.tekton.dev/v1alpha1
                kind: PipelineLoop
                spec:
                  pipelineSpec:
                    params:
                    - name: param-loop-item
                      type: string
                    tasks:
                    - name: print-1
                      taskSpec:
                        steps:
                        - name: main
                          command:
                          - sh
                          - -c
                          - |
                            set -e
                            echo $0 > $1
                          - print
                          - $(results.output-value.path)
                          image: alpine:3.6
                        results:
                        - name: output-value
                          description: /tmp/outputs/output_value/data
                        metadata:
                          labels:
                            pipelines.kubeflow.org/pipelinename: ''
                            pipelines.kubeflow.org/generation: ''
                            pipelines.kubeflow.org/cache_enabled: "true"
                          annotations:
                            pipelines.kubeflow.org/component_spec_digest: '{"name":
                              "print-1", "outputs": [{"description": "Represents an
                              output paramter.", "name": "output_value", "type": "String"}],
                              "version": "print-1@sha256=3b81342bc143f625b58ebdb01e7c83b145880dee807be35c1e16fdb835d46580"}'
                            tekton.dev/template: ''
                      timeout: 525600m
                  iterateParam: param-loop-item
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
          iterateParam: param-loop-item
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
  timeout: 525600m
```

**Additional information:**
Maybe a loop item isn't considered "used" in the loop?

**Environment:**

* Python Version (use `python --version`): 3.9.0
* SDK Version: f083d6f0f24bf42479e1a2f712bb1262c0e02ed8
* Tekton Version (use `tkn version`): irrelevant --- even with implicit passing, it doesn't (I think?) affect nested PipelineLoops
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
