### ISSUE TITLE
bug(sdk) AnySequencer not working inside of loop

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#926]
/kind bug

**What steps did you take and what happened:**

Create a pipeline with a loop and two any-sequencers: one inside of the
loop, one outside of it.

```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import Loop, AnySequencer
from kfp_tekton.compiler import TektonCompiler


class Coder:
  def empty(self):
    return ""


TektonCompiler._get_unique_id_code = Coder.empty


def PrintOp(name: str, msg: str = None):
  if msg is None:
    msg = name
  print_op = load_component_from_text(
  """
  name: %s
  inputs:
  - {name: input_text, type: String, description: 'Represents an input parameter.'}
  outputs:
  - {name: output_value, type: String, description: 'Represents an output paramter.'}
  implementation:
    container:
      image: alpine:3.6
      command:
      - sh
      - -c
      - |
        set -e
        echo $0 > $1
      - {inputValue: input_text}
      - {outputPath: output_value}
  """ % (name)
  )
  return print_op(msg)


@dsl.pipeline("loop-cond2")
def any_sequencer_piepline(param: list = ["a", "b", "c"]):
  op00 = PrintOp("print-00")
  op01 = PrintOp("print-01")
  AnySequencer([op00, op01], "any-seq-0", statusPath="status")

  with Loop(param):
    op10 = PrintOp("print-10")
    op11 = PrintOp("print-11")
    AnySequencer([op10, op11], "any-seq-1", statusPath="status")


if __name__ == '__main__':
  TektonCompiler().compile(any_sequencer_piepline, __file__.replace('.py', '.yaml'))
```

It compiles to the following yaml:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: loop-cond2
  annotations: (...)
spec:
  params:
  - name: param
    value: '["a", "b", "c"]'
  pipelineSpec:
    params:
    - name: param
      default: '["a", "b", "c"]'
    tasks:
    - name: print-00
      taskSpec: (...)
      timeout: 525600m
    - name: print-01
      taskSpec: (...)
      timeout: 525600m
    - name: any-seq-0
      taskSpec:
        steps:
        - name: main
          args:
          - --namespace
          - $(params.pipelineRun-namespace)
          - --prName
          - $(params.pipelineRun-name)
          - --taskList
          - print-00,print-01
          - --statusPath
          - $(results.status.path)
          command:
          - any-task
          image: dspipelines/any-sequencer:latest
        results:
        - name: none
          description: /tmp/outputs/None/data
        metadata: (...)
        params:
        - name: pipelineRun-name
        - name: pipelineRun-namespace
      timeout: 525600m
      params:
      - name: pipelineRun-name
        value: $(context.pipelineRun.name)
      - name: pipelineRun-namespace
        value: $(context.pipelineRun.namespace)
    - name: loop-cond2-for-loop-1
      params:
      - name: param-loop-item
        value: $(params.param)
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: param-loop-item
              type: string
            tasks:
            - name: print-10
              taskSpec: (...)
              timeout: 525600m
            - name: print-11
              taskSpec: (...)
              timeout: 525600m
            - name: any-seq-1
              taskSpec:
                steps:
                - name: main
                  args:
                  - --namespace
                  - $(context.pipelineRun.namespace)
                  - --prName
                  - $(context.pipelineRun.name)
                  - --taskList
                  - print-10,print-11
                  - --statusPath
                  - $(results.status.path)
                  command:
                  - any-task
                  image: dspipelines/any-sequencer:latest
                results:
                - name: status
                  description: /tmp/outputs/status/data
                metadata: (...)
              timeout: 525600m
          iterateParam: param-loop-item
        metadata: (...)
  timeout: 525600m
```

Note how the any-sequencer outside of the loop passes
`$(context.pipelineRun.name)` and `$(context.pipelineRun.namespace)`
indirectly, via `pipelineRun-name` and `pipelineRun-namespace` params,
but the one inside of the loop uses literals instead.

That causes the any-sequencer inside of the loop fail at runtime,
as those placeholders are only resolve at pipeline level, not task
spec level.

**What did you expect to happen:**

Both of the any-sequencers using parameters:

```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: loop-cond2
  annotations: (...)
spec:
  params:
  - name: param
    value: '["a", "b", "c"]'
  pipelineSpec:
    params:
    - name: param
      default: '["a", "b", "c"]'
    tasks:
    - name: print-00
      taskSpec: (...)
      timeout: 525600m
    - name: print-01
      taskSpec: (...)
      timeout: 525600m
    - name: any-seq-0
      taskSpec:
        steps:
        - name: main
          args:
          - --namespace
          - $(params.pipelineRun-namespace)
          - --prName
          - $(params.pipelineRun-name)
          - --taskList
          - print-00,print-01
          - --statusPath
          - $(results.status.path)
          command:
          - any-task
          image: dspipelines/any-sequencer:latest
        results:
        - name: none
          description: /tmp/outputs/None/data
        metadata: (...)
        params:
        - name: pipelineRun-name
        - name: pipelineRun-namespace
      timeout: 525600m
      params:
      - name: pipelineRun-name
        value: $(context.pipelineRun.name)
      - name: pipelineRun-namespace
        value: $(context.pipelineRun.namespace)
    - name: loop-cond2-for-loop-1
      params:
      - name: param-loop-item
        value: $(params.param)
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: param-loop-item
              type: string
            tasks:
            - name: print-10
              taskSpec: (...)
              timeout: 525600m
            - name: print-11
              taskSpec: (...)
              timeout: 525600m
            - name: any-seq-1
              taskSpec:
                steps:
                - name: main
                  args:
                  - --namespace
                  - $(params.pipelineRun-namespace)
                  - --prName
                  - $(params.pipelineRun-name)
                  - --taskList
                  - print-10,print-11
                  - --statusPath
                  - $(results.status.path)
                  command:
                  - any-task
                  image: dspipelines/any-sequencer:latest
                results:
                - name: status
                  description: /tmp/outputs/status/data
                metadata: (...)
                params:
                - name: pipelineRun-name
                - name: pipelineRun-namespace
              timeout: 525600m
              params:
              - name: pipelineRun-name
                value: $(context.pipelineRun.name)
              - name: pipelineRun-namespace
                value: $(context.pipelineRun.namespace)
          iterateParam: param-loop-item
        metadata: (...)
  timeout: 525600m
```

**Additional information:**
It looks like it works just fine as long as the loop isn't embedded
in the PipelineRun, but a separate resource.

Looks like that particular parameter extraction is performed in
`_handle_tekton_pipeline_variables`. Considering the following part:

```python
if 'taskSpec' in task and 'apiVersion' in task['taskSpec']:
    continue
```

...it seems like it simply ignores any embedded custom tasks with
pipeline-like structure, such as loops. It seems to work fine after
adding recursive call there.

**Environment:**

* Python Version (use `python --version`): 3.9.0
* SDK Version: c854c27108147c6e46f76d3c52b2f99a92545387
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
