### ISSUE TITLE
bug(sdk) - Loops: task output ref corrupted if output name starts with task name

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#947]
/kind bug

**What steps did you take and what happened:**
Name the op/task with some name X, and its output with name X-Y (Y being some suffix). Pass that output to a consumer inside of a loop.

```python
import itertools
from typing import Mapping
import yaml

from kfp import dsl, components
from kfp_tekton.tekton import TEKTON_CUSTOM_TASK_IMAGES, Loop
from kfp_tekton.compiler import TektonCompiler


ARTIFACT_FETCHER_IMAGE_NAME = "fetcher/image:latest"
TEKTON_CUSTOM_TASK_IMAGES = TEKTON_CUSTOM_TASK_IMAGES.append(ARTIFACT_FETCHER_IMAGE_NAME)

class Coder:
  def empty(self):
    return ""

TektonCompiler._get_unique_id_code = Coder.empty


def fetcher_op(name: str, artifact_paths: Mapping[str, str]):
  template_yaml = {
    'name': name,
    'description': 'Fetch',
    'inputs': [
      {'name': key, 'type': 'String'}
      for key in artifact_paths.keys()
    ],
    'outputs': [
      {'name': key, 'type': 'String'}
      for key in artifact_paths.keys()
    ],
    'implementation': {
      'container': {
        'image': ARTIFACT_FETCHER_IMAGE_NAME,
        'command': ['sh', '-c'], # irrelevant
        'args': [
          '--apiVersion', 'fetcher.tekton.dev/v1alpha1',
          '--kind', 'FETCHER',
          '--name', 'fetcher_op',
          *itertools.chain(*[
            (f'--{key}', {'inputValue': key})
            for key in artifact_paths.keys()
          ])
        ]
      }
    }
  }
  template_str = yaml.dump(template_yaml, Dumper=yaml.SafeDumper)
  template = components.load_component_from_text(template_str)
  args = {
    key.replace('-', '_'): val
    for key, val in artifact_paths.items()
  }
  op = template(**args)
  op.add_pod_annotation("valid_container", "false")
  return op

def print_op(name: str, messages: Mapping[str, str]):
  inputs = '\n'.join([
    '  - {name: %s, type: String}' % key for key in messages.keys()
  ])
  outputs = '\n'.join([
    '  - {name: %s, type: String}' % key for key in messages.keys()
  ])
  inout_refs = '\n'.join(list(itertools.chain(*[
    (
      '      - {inputValue: %s}' % key,
      '      - {outputPath: %s}' % key,
    ) for key in messages.keys()
  ])))
  print_template_str = """
  name: %s
  inputs:
%s
  outputs:
%s
  implementation:
    container:
      image: alpine:3.6
      command:
      - sh
      - -c
      - ...
%s
  """ % (name, inputs, outputs, inout_refs)
  print_template = components.load_component_from_text(
    print_template_str
  )
  args = {
    key.replace('-', '_'): val
    for key, val in messages.items()
  }
  return print_template(**args)

def string_consumer(name: str, msg: str = None):
  if msg is None:
    msg = name
  template = components.load_component_from_text(
  """
  name: %s
  inputs:
  - {name: input_text, type: String}
  outputs:
  - {name: output_value, type: String}
  implementation:
    container:
      image: alpine:3.6
      command:
      - sh
      - -c
      - |
        set -e
        echo $0 > $1
      - {inputValue: input_text}
      - {outputPath: output_value}
  """ % name
  )
  return template(msg)



@dsl.pipeline("prefixes")
def prefixes(foo: str, li: list = [1,2,3]):

  # custom-task, prefix diff from name
  fetch_00 = fetcher_op('foo-00', {'bar-00-val': foo})

  # custom-task, prefix same as name
  fetch_01 = fetcher_op('foo-01', {'foo-01-val': foo})

  # custom-task, param name identical to name
  fetch_02 = fetcher_op('foo-02', {'foo-02': foo})

  # normal task, prefix diff from name
  print_10 = print_op('foo-10', {'bar-10-val': foo})

  # normal task, prefix same as name
  print_11 = print_op('foo-11', {'foo-11-val': foo})

  # normal task, param name identical to name
  print_12 = print_op('foo-12', {'foo-12': foo})

  with Loop(li):
    string_consumer('fetch-00', fetch_00.output)
    string_consumer('fetch-01', fetch_01.output)
    string_consumer('fetch-02', fetch_02.output)
    string_consumer('print-10', print_10.output)
    string_consumer('print-11', print_11.output)
    string_consumer('print-12', print_12.output)


if __name__ == '__main__':
  TektonCompiler().compile(prefixes, __file__.replace('.py', '.yaml'))
```

Here is the output for embedded case:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: prefixes
  annotations: (...)
spec:
  params:
  - name: foo
    value: ''
  - name: li
    value: '[1, 2, 3]'
  pipelineSpec:
    params:
    - name: foo
    - name: li
      default: '[1, 2, 3]'
    tasks:
    (...)
    - runAfter:
      - foo-00
      - foo-01
      - foo-02
      - foo-10
      - foo-11
      - foo-12
      name: prefixes-for-loop-1
      params:
      - name: foo-00-bar-00-val
        value: $(tasks.foo-00.results.bar-00-val)
      - name: foo-01-foo-01-val
        value: $(tasks.foo-01.results.val)
      - name: foo-02-foo-02
        value: $(tasks.foo-02.results.foo-02)
      - name: foo-10-bar-10-val
        value: $(tasks.foo-10.results.bar-10-val)
      - name: foo-11-foo-11-val
        value: $(tasks.foo-11.results.val)
      - name: foo-12-foo-12
        value: $(tasks.foo-12.results.foo-12)
      - name: li-loop-item
        value: $(params.li)
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: foo-00-bar-00-val
              type: string
            - name: foo-01-foo-01-val
              type: string
            - name: foo-02-foo-02
              type: string
            - name: foo-10-bar-10-val
              type: string
            - name: foo-11-foo-11-val
              type: string
            - name: foo-12-foo-12
              type: string
            - name: li-loop-item
              type: string
            tasks: (...)
          iterateParam: li-loop-item
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
  timeout: 525600m
```

Note that for both custom-tasks and normal tasks, the `foo-XX-val` case is trimmed to `val`.

**What did you expect to happen:**
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: prefixes
  annotations: (...)
spec:
  params:
  - name: foo
    value: ''
  - name: li
    value: '[1, 2, 3]'
  pipelineSpec:
    params:
    - name: foo
    - name: li
      default: '[1, 2, 3]'
    tasks:
    (...)
    - runAfter:
      - foo-00
      - foo-01
      - foo-02
      - foo-10
      - foo-11
      - foo-12
      name: prefixes-for-loop-1
      params:
      - name: foo-00-bar-00-val
        value: $(tasks.foo-00.results.bar-00-val)
      - name: foo-01-foo-01-val
        value: $(tasks.foo-01.results.foo-01-val)
      - name: foo-02-foo-02
        value: $(tasks.foo-02.results.foo-02)
      - name: foo-10-bar-10-val
        value: $(tasks.foo-10.results.bar-10-val)
      - name: foo-11-foo-11-val
        value: $(tasks.foo-11.results.foo-11-val)
      - name: foo-12-foo-12
        value: $(tasks.foo-12.results.foo-12)
      - name: li-loop-item
        value: $(params.li)
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: foo-00-bar-00-val
              type: string
            - name: foo-01-foo-01-val
              type: string
            - name: foo-02-foo-02
              type: string
            - name: foo-10-bar-10-val
              type: string
            - name: foo-11-foo-11-val
              type: string
            - name: foo-12-foo-12
              type: string
            - name: li-loop-item
              type: string
            tasks: (...)
          iterateParam: li-loop-item
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
  timeout: 525600m
```

**Additional information:**
It only works like that when the prefix and suffix are connected with `-` --- `foo10` and `foo10val` won't get that kind of error. This could suggest that some backwards-matching of `(source)-(name)` is performed.

**Environment:**

* Python Version (use `python --version`): 3.9.0
* SDK Version: 3ab41efc922aeac51e8794fdeb59f99a666c1916
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
