### ISSUE TITLE
bug(tekton-catalog) PipelineLoop: trims spaces from first and last element

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#957]
/kind bug

**What steps did you take and what happened:**
Create a pipeline with from-string loop using spaces in all of its items:
```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import Loop
from kfp_tekton.compiler import TektonCompiler


class Coder:
  def empty(self):
    return ""


TektonCompiler._get_unique_id_code = Coder.empty


def PrintOp(name: str, msg: str = None):
  if msg is None:
    msg = name
  print_op = load_component_from_text(
  """
  name: %s
  inputs:
  - {name: input_text, type: String, description: 'Represents an input parameter.'}
  outputs:
  - {name: output_value, type: String, description: 'Represents an output paramter.'}
  implementation:
    container:
      image: alpine:3.6
      command:
      - sh
      - -c
      - |
        set -e
        echo -n "'$0'" > $1
      - {inputValue: input_text}
      - {outputPath: output_value}
  """ % (name)
  )
  return print_op(msg)


@dsl.pipeline("trimmed-loop")
def trimmed_loop(text: str = " a , b , c "):
  with Loop.from_string(text, separator=',') as item:
    PrintOp("print", item)


if __name__ == '__main__':
  TektonCompiler().compile(trimmed_loop, __file__.replace('.py', '.yaml'))
```

The produced yaml seems correct to me:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: trimmed-loop
  annotations:
    tekton.dev/output_artifacts: '{"print": [{"key": "artifacts/$PIPELINERUN/print/output_value.tgz",
      "name": "print-output_value", "path": "/tmp/outputs/output_value/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print": [["output_value", "$(results.output-value.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"default": " a , b , c ",
      "name": "text", "optional": true, "type": "String"}], "name": "trimmed-loop"}'
spec:
  params:
  - name: text
    value: ' a , b , c '
  pipelineSpec:
    params:
    - name: text
      default: ' a , b , c '
    tasks:
    - name: trimmed-loop-for-loop-2
      params:
      - name: loop-item-param-1
        value: ','
      - name: text-loop-item
        value: $(params.text)
      taskSpec:
        apiVersion: custom.tekton.dev/v1alpha1
        kind: PipelineLoop
        spec:
          pipelineSpec:
            params:
            - name: text-loop-item
              type: string
            tasks:
            - name: print
              params:
              - name: text-loop-item
                value: $(params.text-loop-item)
              taskSpec:
                steps:
                - name: main
                  command:
                  - sh
                  - -c
                  - |
                    set -e
                    echo -n "'$0'" > $1
                  - $(inputs.params.text-loop-item)
                  - $(results.output-value.path)
                  image: alpine:3.6
                params:
                - name: text-loop-item
                  type: string
                results:
                - name: output-value
                  description: /tmp/outputs/output_value/data
                metadata:
                  labels:
                    pipelines.kubeflow.org/pipelinename: ''
                    pipelines.kubeflow.org/generation: ''
                    pipelines.kubeflow.org/cache_enabled: "true"
                  annotations:
                    pipelines.kubeflow.org/component_spec_digest: '{"name": "print",
                      "outputs": [{"description": "Represents an output paramter.",
                      "name": "output_value", "type": "String"}], "version": "print@sha256=3d0011585ca9382b7b497c8be4a402d4c1654f8c4e26eebacb6ceb5c119a9bc2"}'
                    tekton.dev/template: ''
              timeout: 525600m
          iterateParam: text-loop-item
          iterateParamStringSeparator: loop-item-param-1
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
  timeout: 525600m
```

Notice the `' a , b , c '`, preserving spaces.

When running it though, the results are:
* `'a '`
* `' b '`
* `' c'`
I.e. cutting the leading space in the first element and the trailing one in the last one.

It also leads to zero iteration instead of one if the text is a space character.

**What did you expect to happen:**
* `' a '`
* `' b '`
* `' c '`

A single-space text should lead to one iteration, not zero.

**Additional information:**
Looks like PipelineLoop controller is using `strings.Trim` on the text.

**Environment:**

* Python Version (use `python --version`): irrelevant
* SDK Version: faa409aa6144647d035c1ac0c58776eafa1f4787
* Tekton Version (use `tkn version`): v0.33.1-beta
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
