### ISSUE TITLE
bug(sdk) by-path literals not working with add_volume

### ISSUE THREAD

**Issue by Udiknedormin** [kubeflow/kfp-tekton#990]
/kind bug

**What steps did you take and what happened:**
To compare various use-cases of big data passing to inputs, I created a pipeline with the following:
* small output passed to small input
* big output passed to small input
* literal passed to small input
* small output passed to big input
* big output passed to big input
* literal passed to big input

All of those are tested with additionally adding a volume and volume-mount.

Most of those produces results that are either as expected or seem correct in the current model (e.g. big -> small which works fine as long as the big output is small enough to fit into its result). But not so for the last case:

Here is the literal use-case, comparing small and big inputs:
```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.compiler import TektonCompiler
from kubernetes.client import V1Volume, V1VolumeMount, V1SecretVolumeSource


def PrintOp(name: str, msg: str = None):
  if msg is None:
    msg = name
  print_op = load_component_from_text(
  """
  name: %s
  inputs:
  - {name: input_text, type: String, description: 'Represents an input parameter.'}
  outputs:
  - {name: output_value, type: String, description: 'Represents an output paramter.'}
  implementation:
    container:
      image: alpine:3.6
      command:
      - sh
      - -c
      - |
        set -e
        echo $0 > $1
      - {inputValue: input_text}
      - {outputPath: output_value}
  """ % name
  )
  return print_op(msg)

def PrintRefOp(name: str, msg: str = None):
  if msg is None:
    msg = name
  print_op = load_component_from_text(
  """
  name: %s
  inputs:
  - {name: input_text, type: String, description: 'Represents an input parameter.'}
  outputs:
  - {name: output_value, type: String, description: 'Represents an output paramter.'}
  implementation:
    container:
      image: alpine:3.6
      command:
      - sh
      - -c
      - |
        set -e
        cat $0 > $1
      - {inputPath: input_text}
      - {outputPath: output_value}
  """ % name
  )
  return print_op(msg)

def add_volume_and_mount(op: dsl.ContainerOp) -> dsl.ContainerOp:
    suffix = op.name[op.name.index('-'):]
    return op.add_volume(
        V1Volume(
            name='volume' + suffix,
            secret=V1SecretVolumeSource(secret_name='secret' + suffix),
        )
    ).container.add_volume_mount(
        V1VolumeMount(
            name='volume' + suffix,
            mount_path='/volume' + suffix,
        )
    )

@dsl.pipeline(name='big-data')
def big_data():
    # literal -> small
    PrintOp(
        'print-sm',
        'literal',
    ).apply(add_volume_and_mount)

    # literal -> big
    PrintRefOp(
        'print-big',
        'literal',
    ).apply(add_volume_and_mount)


if __name__ == '__main__':
    from kfp_tekton.compiler import TektonCompiler
    TektonCompiler().compile(big_data, __file__.replace('.py', '.yaml'))
```

And here is the yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: big-data
  annotations:
    tekton.dev/output_artifacts: '{"print-big": [{"key": "artifacts/$PIPELINERUN/print-big/output_value.tgz",
      "name": "print-big-output_value", "path": "/tmp/outputs/output_value/data"}],
      "print-sm": [{"key": "artifacts/$PIPELINERUN/print-sm/output_value.tgz", "name":
      "print-sm-output_value", "path": "/tmp/outputs/output_value/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print-big": [["output_value", "$(results.output-value.path)"]],
      "print-sm": [["output_value", "$(results.output-value.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"name": "big-data"}'
spec:
  pipelineSpec:
    tasks:
    - name: print-sm
      taskSpec:
        steps:
        - name: main
          command:
          - sh
          - -c
          - |
            set -e
            echo $0 > $1
          - literal
          - $(results.output-value.path)
          image: alpine:3.6
          volumeMounts:
          - mountPath: /volume-sm
            name: volume-sm
        results:
        - name: output-value
          type: string
          description: /tmp/outputs/output_value/data
        volumes:
        - name: volume-sm
          secret:
            secretName: secret-sm
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "print-sm", "outputs":
              [{"description": "Represents an output paramter.", "name": "output_value",
              "type": "String"}], "version": "print-sm@sha256=05ff13424ebfe972a875c7a9547e21a7b6c947276fac53c4b53e15925f38912d"}'
            tekton.dev/template: ''
      timeout: 525600m
    - name: print-big
      taskSpec:
        steps:
        - image: busybox
          name: copy-inputs
          script: |
            #!/bin/sh
            set -exo pipefail
            echo -n "literal" > /tmp/inputs/input_text/data
        - name: main
          command:
          - sh
          - -c
          - |
            set -e
            cat $0 > $1
          - /tmp/inputs/input_text/data
          - $(results.output-value.path)
          image: alpine:3.6
          volumeMounts:
          - mountPath: /volume-big
            name: volume-big
        results:
        - name: output-value
          type: string
          description: /tmp/outputs/output_value/data
        volumes:
        - name: input-text
          emptyDir: {}
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "print-big", "outputs":
              [{"description": "Represents an output paramter.", "name": "output_value",
              "type": "String"}], "version": "print-big@sha256=c6abb29210bc5e418b9fe92d3c3bdc912ae568f179e899c27cc2b04aa884abb7"}'
            tekton.dev/template: ''
        stepTemplate:
          volumeMounts:
          - name: input-text
            mountPath: /tmp/inputs/input_text
      timeout: 525600m
  timeout: 525600m
```

Notably, small-input case has a `volume-sm` volume, matching the volume mount:
```yaml
  volumeMounts:
  - mountPath: /volume-sm
    name: volume-sm
volumes:
- name: volume-sm
  secret:
    secretName: secret-sm
```

However, for big-input case while the `volume-big` volume mount is present, its volume is not:
```yaml
  volumeMounts:
  - mountPath: /volume-big
    name: volume-big
volumes:
- name: input-text
  emptyDir: {}
stepTemplate:
  volumeMounts:
  - name: input-text
    mountPath: /tmp/inputs/input_text
```

**What did you expect to happen:**
The big-input case should generate the volume as in small-input case:
```yaml
  volumeMounts:
  - mountPath: /volume-big
    name: volume-big
volumes:
- name: input-text
  emptyDir: {}
- name: volume-big
  secret:
    secretName: secret-big
stepTemplate:
  volumeMounts:
  - name: input-text
    mountPath: /tmp/inputs/input_text
```

The ordering of those volumes is irrelevant, so it could be the other way around too:
```yaml
  volumeMounts:
  - mountPath: /volume-big
    name: volume-big
volumes:
- name: volume-big
  secret:
    secretName: secret-big
- name: input-text
  emptyDir: {}
stepTemplate:
  volumeMounts:
  - name: input-text
    mountPath: /tmp/inputs/input_text
```

**Additional information:**
I can see two code pieces that seem related:
```python
def _update_volumes(template: Dict[Text, Any],
                    volume_mount_step_template: List[Dict[Text, Any]],
                    volume_template: List[Dict[Text, Any]]):
    """
    Update the list of volumes and volumeMounts on a given template
    """
    if volume_mount_step_template:
        template['spec']['stepTemplate'] = {}
        template['spec']['stepTemplate']['volumeMounts'] = volume_mount_step_template
        template['spec']['volumes'] = volume_template

(...)

def _op_to_template(op: BaseOp,
                    pipelinerun_output_artifacts={},
                    artifact_items={}):
    """Generate template given an operator inherited from BaseOp."""

    # Display name
    if op.display_name:
        op.add_pod_annotation('pipelines.kubeflow.org/task_display_name', op.display_name)

    # initial local variables for tracking volumes and artifacts
    volume_mount_step_template = []
    volume_template = []
   (...)
        _update_volumes(template, volume_mount_step_template, volume_template)
   (...)
```
and:
```python
def input_artifacts_tasks(template: dict, artifact: dict) -> dict:
    # The input artifacts in KFP is not pulling from s3, it will always be passed as a raw input.
    # Visit https://github.com/kubeflow/pipelines/issues/336 for more details on the implementation.
    volume_mount_step_template = []
    volume_template = []
    mounted_param_paths = []
    copy_inputs_step = _get_base_step('copy-inputs')
    if 'raw' in artifact:
        copy_inputs_step['script'] += 'echo -n "%s" > %s\n' % (
            artifact['raw']['data'], artifact['path'])
    mount_path = artifact['path'].rsplit("/", 1)[0]
    if mount_path not in mounted_param_paths:
        _add_mount_path(artifact['name'], artifact['path'], mount_path,
                        volume_mount_step_template, volume_template,
                        mounted_param_paths)
    template['taskSpec']['steps'] = _prepend_steps(
        [copy_inputs_step], template['taskSpec']['steps'])
    # _update_volumes(template, volume_mount_step_template, volume_template)
    if volume_mount_step_template:
        template['taskSpec']['stepTemplate'] = {}
        template['taskSpec']['stepTemplate']['volumeMounts'] = volume_mount_step_template
        template['taskSpec']['volumes'] = volume_template
    return template
```

Notably, `volume_template` and `volume_mount_step_template` are initialized as empty lists in both cases. It looks like the volume list by the `add_volume` is simply overwritten.

In the first piece of code, `.volumes` are included below. But in he latter, it seems it's overwritten. While there is `_add_mount_path` earlier on that should append to `mounted_param_paths` list --- that list is created as empty each time and overwrites the volumes and volume mounts. `input_artifacts_tasks` is called in a loop for every artifact though:
```python
for task_artifact in task_artifacts:
    if (task_name, task_artifact.get('name')) not in inputs_tasks:
        # add input artifact processes
        task = input_artifacts_tasks(task, task_artifact)
```
Which would suggest it will be overwritten in case of multiple artifacts.

Test: if that is the case, them two big-inputs should only generate a single volume and volumeMount in stepTemplate.
```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.compiler import TektonCompiler
from kubernetes.client import V1Volume, V1VolumeMount, V1SecretVolumeSource


def PrintOp(name: str, msg0: str = None, msg1: str = None):
  if msg0 is None:
    msg0 = name
  if msg1 is None:
    msg1 = msg0
  print_op = load_component_from_text(
  """
  name: %s
  inputs:
  - {name: input_text_0, type: String, description: 'Represents an input parameter.'}
  - {name: input_text_1, type: String, description: 'Represents an input parameter.'}
  outputs:
  - {name: output_value, type: String, description: 'Represents an output paramter.'}
  implementation:
    container:
      image: alpine:3.6
      command:
      - sh
      - -c
      - |
        set -e
        echo $0 >> $2
        echo $1 >> $2
      - {inputValue: input_text_0}
      - {inputValue: input_text_1}
      - {outputPath: output_value}
  """ % name
  )
  return print_op(msg0, msg1)

def PrintRefOp(name: str, msg0: str = None, msg1: str = None):
  if msg0 is None:
    msg0 = name
  if msg1 is None:
    msg1 = msg0
  print_op = load_component_from_text(
  """
  name: %s
  inputs:
  - {name: input_text_0, type: String, description: 'Represents an input parameter.'}
  - {name: input_text_1, type: String, description: 'Represents an input parameter.'}
  outputs:
  - {name: output_value, type: String, description: 'Represents an output paramter.'}
  implementation:
    container:
      image: alpine:3.6
      command:
      - sh
      - -c
      - |
        set -e
        cat $0 >> $2
        cat $1 >> $2
      - {inputPath: input_text_0}
      - {inputPath: input_text_1}
      - {outputPath: output_value}
  """ % name
  )
  return print_op(msg0, msg1)

def add_volume_and_mount(op: dsl.ContainerOp) -> dsl.ContainerOp:
    suffix = op.name[op.name.index('-'):]
    return op.add_volume(
        V1Volume(
            name='volume' + suffix,
            secret=V1SecretVolumeSource(secret_name='secret' + suffix),
        )
    ).container.add_volume_mount(
        V1VolumeMount(
            name='volume' + suffix,
            mount_path='/volume' + suffix,
        )
    )

@dsl.pipeline(name='big-data')
def big_data():
    # literal -> small
    PrintOp(
        'print-sm',
        'literal0',
        'literal1',
    ).apply(add_volume_and_mount)

    # literal -> big
    PrintRefOp(
        'print-big',
        'literal0',
        'literal1',
    ).apply(add_volume_and_mount)


if __name__ == '__main__':
    from kfp_tekton.compiler import TektonCompiler
    TektonCompiler().compile(big_data, __file__.replace('.py', '.yaml'))
```

Yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: big-data
  annotations:
    tekton.dev/output_artifacts: '{"print-big": [{"key": "artifacts/$PIPELINERUN/print-big/output_value.tgz",
      "name": "print-big-output_value", "path": "/tmp/outputs/output_value/data"}],
      "print-sm": [{"key": "artifacts/$PIPELINERUN/print-sm/output_value.tgz", "name":
      "print-sm-output_value", "path": "/tmp/outputs/output_value/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print-big": [["output_value", "$(results.output-value.path)"]],
      "print-sm": [["output_value", "$(results.output-value.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/big_data_passing_format: $(workspaces.$TASK_NAME.path)/artifacts/$ORIG_PR_NAME/$TASKRUN_NAME/$TASK_PARAM_NAME
    pipelines.kubeflow.org/pipeline_spec: '{"name": "big-data"}'
spec:
  pipelineSpec:
    tasks:
    - name: print-sm
      taskSpec:
        steps:
        - name: main
          command:
          - sh
          - -c
          - |
            set -e
            echo $0 >> $2
            echo $1 >> $2
          - literal0
          - literal1
          - $(results.output-value.path)
          image: alpine:3.6
          volumeMounts:
          - mountPath: /volume-sm
            name: volume-sm
        results:
        - name: output-value
          type: string
          description: /tmp/outputs/output_value/data
        volumes:
        - name: volume-sm
          secret:
            secretName: secret-sm
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "print-sm", "outputs":
              [{"description": "Represents an output paramter.", "name": "output_value",
              "type": "String"}], "version": "print-sm@sha256=cf0e0bcc0df84c91fa64613cbc1ce2006fce9f66a9bc5645d35018388a2b8137"}'
            tekton.dev/template: ''
      timeout: 525600m
    - name: print-big
      taskSpec:
        steps:
        - image: busybox
          name: copy-inputs
          script: |
            #!/bin/sh
            set -exo pipefail
            echo -n "literal1" > /tmp/inputs/input_text_1/data
        - image: busybox
          name: copy-inputs
          script: |
            #!/bin/sh
            set -exo pipefail
            echo -n "literal0" > /tmp/inputs/input_text_0/data
        - name: main
          command:
          - sh
          - -c
          - |
            set -e
            cat $0 >> $2
            cat $1 >> $2
          - /tmp/inputs/input_text_0/data
          - /tmp/inputs/input_text_1/data
          - $(results.output-value.path)
          image: alpine:3.6
          volumeMounts:
          - mountPath: /volume-big
            name: volume-big
        results:
        - name: output-value
          type: string
          description: /tmp/outputs/output_value/data
        volumes:
        - name: input-text-1
          emptyDir: {}
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec_digest: '{"name": "print-big", "outputs":
              [{"description": "Represents an output paramter.", "name": "output_value",
              "type": "String"}], "version": "print-big@sha256=3fa808af9aecedcb63c7c9953431ca4bd24cbf79150497d5e3651afe7347f97a"}'
            tekton.dev/template: ''
        stepTemplate:
          volumeMounts:
          - name: input-text-1
            mountPath: /tmp/inputs/input_text_1
      timeout: 525600m
  timeout: 525600m
```

Indeed, the big-input case only has:
```yaml
volumes:
- name: input-text-1
  emptyDir: {}
stepTemplate:
  volumeMounts:
  - name: input-text-1
    mountPath: /tmp/inputs/input_text_1
```
while what was expected is:
```yaml
volumes:
- name: input-text-0
  emptyDir: {}
- name: input-text-1
  emptyDir: {}
stepTemplate:
  volumeMounts:
  - name: input-text-0
    mountPath: /tmp/inputs/input_text_0
  - name: input-text-1
    mountPath: /tmp/inputs/input_text_1
```

It seems that list should therefore be factored out and setting volumes and volumeMounts --- to appending to them.

**Environment:**

* Python Version (use `python --version`): 3.9.0
* SDK Version: bce98146514432c1967297843bfc1014011482c8
* Tekton Version (use `tkn version`): irrelevant
* Kubernetes Version (use `kubectl version`): irrelevant
* OS (e.g. from `/etc/os-release`): irrelevant
